## Top 8 Powerful Functions in Python for Deeper Data Analysis

1. GroupBy
2. pivot_table
3. Aggregate
4. cross_tab
5. concat
6. apply
7. lambda
8. del(Keyword)

## 1.Groupby Function

In [149]:
import pandas as pd

insurance_data = pd.read_csv("insurance.csv")
insurance_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

### 1.1 Perform Initial Analysis

In [5]:
insurance_data.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [7]:
insurance_data.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [10]:
insurance_data.describe(include = "all")

,age,sex,bmi,children,smoker,region,charges
count,1338.000000,1338,1338.000000,1338.000000,1338,1338,1338.000000
unique,NaN,2,NaN,NaN,2,4,NaN
top,NaN,male,NaN,NaN,no,southeast,NaN
freq,NaN,676,NaN,NaN,1064,364,NaN
mean,39.207025,NaN,30.663397,1.094918,NaN,NaN,13270.422265
std,14.049960,NaN,6.098187,1.205493,NaN,NaN,12110.011237
min,18.000000,NaN,15.960000,0.000000,NaN,NaN,1121.873900
25%,27.000000,NaN,26.296250,0.000000,NaN,NaN,4740.287150
50%,39.000000,NaN,30.400000,1.000000,NaN,NaN,9382.033000
75%,51.000000,NaN,34.693750,2.000000,NaN,NaN,16639.912515
max,64.000000,NaN,53.130000,5.000000,NaN,NaN,63770.428010

In [12]:
insurance_data["region"].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

### 1.2 Pull up the Insurance Charges based on Region

In [23]:
insurance_data.groupby(by="region")["charges"].mean().sort_values().round(2)

region
southwest    12346.94
northwest    12417.58
northeast    13406.38
southeast    14735.41
Name: charges, dtype: float64

In [24]:
insurance_data.groupby(by="region")["charges"].mean().sort_values(ascending=False).round(2)

region
southeast    14735.41
northeast    13406.38
northwest    12417.58
southwest    12346.94
Name: charges, dtype: float64

### 1.2 Pull up the average Insurance charges based on region and sex

#### Discrete / categorical data and Continous data

* Discrete - Just countable / Can't be segmented
* Continous - Measurable / Have Units / can be segmented

### NOTE : 

### In this groupby function(by -> it should contains one or more but the values must be discrete) [" " -> Outside it should contain only continous]

In [25]:
insurance_data.head(7)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
5   31  female  25.740         0     no  southeast   3756.62160
6   46  female  33.440         1     no  southeast   8240.58960

In [27]:
insurance_data.groupby(by=["region","sex"])["charges"].mean().sort_values(ascending=False).round(2)

region     sex
southeast  male      15879.62
northeast  male      13854.01
southeast  female    13499.67
southwest  male      13412.88
northeast  female    12953.20
northwest  female    12479.87
           male      12354.12
southwest  female    11274.41
Name: charges, dtype: float64

In [28]:
insurance_data.groupby(by=["region","sex"])["charges"].max().sort_values(ascending=False).round(2)

region     sex
southeast  female    63770.43
           male      62592.87
northwest  male      60021.40
northeast  female    58571.07
northwest  female    55135.40
southwest  male      52590.83
           female    48824.45
northeast  male      48549.18
Name: charges, dtype: float64

## 2.Pivot Table

In [34]:
pd.pivot_table( data=insurance_data, values="charges", index="region", columns="sex").round() #presentable comparing 2 categorical features vs  1 continous data

sex         female     male
region
northeast  12953.0  13854.0
northwest  12480.0  12354.0
southeast  13500.0  15880.0
southwest  11274.0  13413.0

In [35]:
pd.pivot_table( data=insurance_data, values="charges", index="region", columns=["sex","children"]).round()

sex         female                                                  male  \
children         0        1        2        3        4        5        0
region
northeast   9790.0  17125.0  14523.0  13730.0  14542.0      NaN  13390.0
northwest  12584.0  11119.0  13128.0  13431.0  11024.0   8966.0   9813.0
southeast  14862.0   9870.0  11766.0  19723.0  18267.0   9924.0  13792.0
southwest  10150.0  10842.0  16230.0   8439.0  10946.0  10024.0  13727.0

sex
children         1        2        3        4        5
region
northeast  15474.0  12318.0  14935.0  14442.0   6979.0
northwest   9515.0  13763.0  22971.0  11508.0      NaN
southeast  17425.0  18648.0  17102.0   8727.0  10307.0
southwest   9971.0  18876.0  12072.0  17924.0   6865.0

## 3.Aggregate

In [36]:
insurance_data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

### 3.1 Find out the average Insurance charges based on Region

In [37]:
insurance_data.groupby(by="region")["charges"].mean().sort_values().round(2)

region
southwest    12346.94
northwest    12417.58
northeast    13406.38
southeast    14735.41
Name: charges, dtype: float64

In [39]:
insurance_data.groupby(by=["region","sex"])["charges"].agg(func = ["mean","min","max","sum"]).round()

                     mean     min      max        sum
region    sex
northeast female  12953.0  2196.0  58571.0  2085466.0
          male    13854.0  1695.0  48549.0  2258203.0
northwest female  12480.0  2117.0  55135.0  2046699.0
          male    12354.0  1621.0  60021.0  1989013.0
southeast female  13500.0  1608.0  63770.0  2362442.0
          male    15880.0  1122.0  62593.0  3001248.0
southwest female  11274.0  1728.0  48824.0  1826455.0
          male    13413.0  1242.0  52591.0  2186300.0

## 4.CrossTab

Compare two categorical data to come up with a frequency

### 4.1 How many smokers and non-smokers based on region?

In [40]:
insurance_data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

## NOTE:

In [58]:
insurance_data.age

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

In [59]:
insurance_data["age"]

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

insurance_data[["age","charges"]]

In [42]:
pd.crosstab(index = insurance_data["region"] ,columns = insurance_data["smoker"] , margins = True)

smoker       no  yes   All
region
northeast   257   67   324
northwest   267   58   325
southeast   273   91   364
southwest   267   58   325
All        1064  274  1338

In [45]:
pd.crosstab(index = insurance_data["region"] ,columns = insurance_data["sex"] , margins = True)

sex        female  male   All
region
northeast     161   163   324
northwest     164   161   325
southeast     175   189   364
southwest     162   163   325
All           662   676  1338

In [46]:
pd.crosstab(index = insurance_data["region"] ,columns = insurance_data["age"] , margins = True)

age,18,19,20,21,22,23,24,25,26,27,...,56,57,58,59,60,61,62,63,64,All
region,,,,,,,,,,,,,,,,,,,,,
northeast,32,0,6,7,7,7,7,7,7,7,...,7,7,6,6,6,6,6,5,4,324
northwest,0,34,7,7,7,7,7,7,7,6,...,6,7,7,5,5,6,6,6,5,325
southeast,37,3,8,7,8,7,7,7,7,9,...,6,6,6,8,6,5,6,6,8,364
southwest,0,31,8,7,6,7,7,7,7,6,...,7,6,6,6,6,6,5,6,5,325
All,69,68,29,28,28,28,28,28,28,28,...,26,26,25,25,23,23,23,23,22,1338

## 5.Concat

In [48]:
sales_data_2017 = pd.read_csv("Sales Transactions-2017.csv")
sales_data_2018 = pd.read_csv("Sales Transactions-2018.csv")
sales_data_2019 = pd.read_csv("Sales Transactions-2019.csv")

In [57]:
sales_full_data = pd.concat(objs = [sales_data_2017,sales_data_2018,sales_data_2019])  #concat means placed the files one by one - same column dataset
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [54]:
sales_edited_data = pd.read_csv("Sales-Transactions-Edited.csv")
sales_edited_data

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
95557,12/9/2019,4265,TP13,SPOON MED M.W,20,11.0
95558,12/9/2019,4266,K.SRIHARI,SMART BOUL(48),1,1830.0
95559,12/9/2019,4267,SMS,SMARTBOUL GLA(4000),1,1520.0
95560,12/9/2019,4268,ANILFANCY,RR WINEGLASS,100,20.0
95561,12/9/2019,4268,ANILFANCY,RR WATER GLASS,100,20.0

## 6.Apply

In [61]:
insurance_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [63]:
insurance_data.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

#### 6.1 Create a new column in the same dataframe with the name "Eligibility Criteria" where if age is is > 20, say Eligible else not

In [66]:
insurance_data["age"] > 20

0       False
1       False
2        True
3        True
4        True
        ...
1333     True
1334    False
1335    False
1336     True
1337     True
Name: age, Length: 1338, dtype: bool

In [67]:
if insurance_data["age"] > 20:
    print("Eligible")
else:
    print("Not Eligible")

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [122]:
def get_age(x):
    if x > 20:
          print("Eligible")
    else:
          print("Not Eligible")

In [1]:
insurance_data["Eligibility criteria"] = insurance_data["age"].apply( get_age)
insurance_data

NameError: name 'insurance_data' is not defined

In [140]:
def get_age(x):
    if x > 20:
         return "Eligible"
    else:
         return "Not Eligible"

In [141]:
insurance_data["Eligibility criteria"] = insurance_data["age"].apply( get_age)
insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligibility criteria,EC
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible,Not eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible,Not eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible,Eligible
...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible,Not eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible,Not eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible,Eligible

## 7.Lambda

It is also called as Anonymous function or Nameless function

In [135]:
insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligibility criteria
0,19,female,27.900,0,yes,southwest,16884.92400,Eligible
1,18,male,33.770,1,no,southeast,1725.55230,Eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible

In [136]:
insurance_data["age"].apply(lambda x:"Eligible" if x>20 else "Not eligible")

0       Not eligible
1       Not eligible
2           Eligible
3           Eligible
4           Eligible
            ...
1333        Eligible
1334    Not eligible
1335    Not eligible
1336        Eligible
1337        Eligible
Name: age, Length: 1338, dtype: object

In [143]:
insurance_data["EC"] = insurance_data["age"].apply(lambda x:"Eligible" if x>20 else "Not eligible")
insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligibility criteria,EC
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible,Not eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible,Not eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible,Eligible
...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible,Not eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible,Not eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible,Eligible

## 8.Del keyword

Delete one column at a time

In [159]:
import pandas as pd

insurance_data = pd.read_csv("insurance.csv")
insurance_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [160]:
del insurance_data["charges"]
insurance_data

      age     sex     bmi  children smoker     region
0      19  female  27.900         0    yes  southwest
1      18    male  33.770         1     no  southeast
2      28    male  33.000         3     no  southeast
3      33    male  22.705         0     no  northwest
4      32    male  28.880         0     no  northwest
...   ...     ...     ...       ...    ...        ...
1333   50    male  30.970         3     no  northwest
1334   18  female  31.920         0     no  northeast
1335   18  female  36.850         0     no  southeast
1336   21  female  25.800         0     no  southwest
1337   61  female  29.070         0    yes  northwest

[1338 rows x 6 columns]