## Chapter 1: Getting & Knowing your Data

1. Business Understanding
2. Data collection
3. Data Understanding
4. Data Preparation

In [2]:
import pandas as pd

In [18]:
order_details = pd.read_csv(filepath_or_buffer = "data.tsv.txt" ,sep = "\t")   #tsv is tab separated file
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [13]:
pd.read_table(filepath_or_buffer = "insurance.csv")  #csv is comma separated file

      age,sex,bmi,children,smoker,region,charges
0       19,female,27.9,0,yes,southwest,16884.924
1         18,male,33.77,1,no,southeast,1725.5523
2             28,male,33,3,no,southeast,4449.462
3      33,male,22.705,0,no,northwest,21984.47061
4         32,male,28.88,0,no,northwest,3866.8552
...                                          ...
1333     50,male,30.97,3,no,northwest,10600.5483
1334    18,female,31.92,0,no,northeast,2205.9808
1335    18,female,36.85,0,no,southeast,1629.8335
1336      21,female,25.8,0,no,southwest,2007.945
1337  61,female,29.07,0,yes,northwest,29141.3603

[1338 rows x 1 columns]

In [14]:
pd.read_table(filepath_or_buffer = "insurance.csv" , sep = ",")

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [20]:
order_details = pd.read_table(filepath_or_buffer =  "data.tsv.txt")
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### 1.1 Perform Initial Analysis

In [22]:
# Function - ()
# Attribute - It doesn't needs to enclose by an paranthesis

In [21]:
order_details.shape

(4622, 5)

#### Terminology Alert
* Rows - Observations or Records
* Columns - Features or Parameters

In [23]:
order_details.isnull()

      order_id  quantity  item_name  choice_description  item_price
0        False     False      False                True       False
1        False     False      False               False       False
2        False     False      False               False       False
3        False     False      False                True       False
4        False     False      False               False       False
...        ...       ...        ...                 ...         ...
4617     False     False      False               False       False
4618     False     False      False               False       False
4619     False     False      False               False       False
4620     False     False      False               False       False
4621     False     False      False               False       False

[4622 rows x 5 columns]

In [25]:
order_details.isnull().sum()  #Performing more than one functions - Chain of Functions or Chain of Commands

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [26]:
order_details.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [32]:
order_details.describe() #First the describe function consider the int dtypes

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

In [34]:
order_details.describe(include = "all") #Whenever you include all , it considers the all datatypes

           order_id     quantity     item_name choice_description item_price
count   4622.000000  4622.000000          4622               3376       4622
unique          NaN          NaN            50               1043         78
top             NaN          NaN  Chicken Bowl        [Diet Coke]     $8.75
freq            NaN          NaN           726                134        730
mean     927.254868     1.075725           NaN                NaN        NaN
std      528.890796     0.410186           NaN                NaN        NaN
min        1.000000     1.000000           NaN                NaN        NaN
25%      477.250000     1.000000           NaN                NaN        NaN
50%      926.000000     1.000000           NaN                NaN        NaN
75%     1393.000000     1.000000           NaN                NaN        NaN
max     1834.000000    15.000000           NaN                NaN        NaN

### 1.2 Find out the Items sold in the Restaurent

In [35]:
order_details.nunique()

order_id              1834
quantity                 9
item_name               50
choice_description    1043
item_price              78
dtype: int64

In [38]:
print(order_details["item_name"].unique())

['Chips and Fresh Tomato Salsa' 'Izze' 'Nantucket Nectar'
 'Chips and Tomatillo-Green Chili Salsa' 'Chicken Bowl' 'Side of Chips'
 'Steak Burrito' 'Steak Soft Tacos' 'Chips and Guacamole'
 'Chicken Crispy Tacos' 'Chicken Soft Tacos' 'Chicken Burrito'
 'Canned Soda' 'Barbacoa Burrito' 'Carnitas Burrito' 'Carnitas Bowl'
 'Bottled Water' 'Chips and Tomatillo Green Chili Salsa' 'Barbacoa Bowl'
 'Chips' 'Chicken Salad Bowl' 'Steak Bowl' 'Barbacoa Soft Tacos'
 'Veggie Burrito' 'Veggie Bowl' 'Steak Crispy Tacos'
 'Chips and Tomatillo Red Chili Salsa' 'Barbacoa Crispy Tacos'
 'Veggie Salad Bowl' 'Chips and Roasted Chili-Corn Salsa'
 'Chips and Roasted Chili Corn Salsa' 'Carnitas Soft Tacos'
 'Chicken Salad' 'Canned Soft Drink' 'Steak Salad Bowl'
 '6 Pack Soft Drink' 'Chips and Tomatillo-Red Chili Salsa' 'Bowl'
 'Burrito' 'Crispy Tacos' 'Carnitas Crispy Tacos' 'Steak Salad'
 'Chips and Mild Fresh Tomato Salsa' 'Veggie Soft Tacos'
 'Carnitas Salad Bowl' 'Barbacoa Salad Bowl' 'Salad' 'Veggie Crispy Tacos'
 'Veggie Salad' 'Carnitas Salad']

### 1.3 Give me the list of Top 5 Items

In [46]:
order_details.groupby(by="item_name")["quantity"].sum().sort_values(ascending = False).head()

item_name
Chicken Bowl           761
Chicken Burrito        591
Chips and Guacamole    506
Steak Burrito          386
Canned Soft Drink      351
Name: quantity, dtype: int64

### 1.3 Give me the list of Least 5 Selling Items

In [49]:
order_details.groupby(by="item_name")["quantity"].sum().sort_values().head(10)

item_name
Carnitas Salad                       1
Chips and Mild Fresh Tomato Salsa    1
Veggie Crispy Tacos                  1
Crispy Tacos                         2
Salad                                2
Steak Salad                          4
Bowl                                 4
Burrito                              6
Carnitas Salad Bowl                  6
Veggie Salad                         6
Name: quantity, dtype: int64

## Chapter 2: Data Cleaning

In [50]:
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [51]:
order_details.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [54]:
order_details["item_price"].str.replace("$","")

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
         ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: object

In [55]:
order_details["item_price"].str.replace("$","").float()

AttributeError: 'Series' object has no attribute 'float'

In [ ]:
# "Series"

In [ ]:
order_details["item_price"] = order_details["item_price"].str.replace("$","").astype(float)

In [85]:
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [87]:
order_details.dtypes

order_id                int64
quantity                int64
item_name              object
choice_description     object
item_price            float64
dtype: object

In [88]:
order_details.describe()

          order_id     quantity   item_price
count  4622.000000  4622.000000  4622.000000
mean    927.254868     1.075725     7.464336
std     528.890796     0.410186     4.245557
min       1.000000     1.000000     1.090000
25%     477.250000     1.000000     3.390000
50%     926.000000     1.000000     8.750000
75%    1393.000000     1.000000     9.250000
max    1834.000000    15.000000    44.250000

## Chapter 3: Pandas Data Structure

* 1D - Series
* 2D - DataFrame

In [91]:
pd.Series(data = [1,2,3,"$2.5",3.4])

0       1
1       2
2       3
3    $2.5
4     3.4
dtype: object

In [92]:
pd.DataFrame( {"Name":["Yujin","Malini","Love","Valentine"],"Maths":[67,89,100,34],"Science":[100,90,80,70]})

        Name  Maths  Science
0      Yujin     67      100
1     Malini     89       90
2       Love    100       80
3  Valentine     34       70

## Chapter 4: Filtering & Selecting & Sorting

In [95]:
euro_2012_data = pd.read_csv("Euro_2012_stats_TEAM.csv")
euro_2012_data

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

In [96]:
euro_2012_data.columns

Index(['Team', 'Goals', 'Shots on target', 'Shots off target',
       'Shooting Accuracy', '% Goals-to-shots', 'Total shots (inc. Blocked)',
       'Hit Woodwork', 'Penalty goals', 'Penalties not scored', 'Headed goals',
       'Passes', 'Passes completed', 'Passing Accuracy', 'Touches', 'Crosses',
       'Dribbles', 'Corners Taken', 'Tackles', 'Clearances', 'Interceptions',
       'Clearances off line', 'Clean Sheets', 'Blocks', 'Goals conceded',
       'Saves made', 'Saves-to-shots ratio', 'Fouls Won', 'Fouls Conceded',
       'Offsides', 'Yellow Cards', 'Red Cards', 'Subs on', 'Subs off',
       'Players Used'],
      dtype='object')

In [102]:
pd.set_option("display.max_columns",None)  #For viewing the all columns in the dataframe

In [101]:
euro_2012_data

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed,Passing Accuracy,Touches,Crosses,Dribbles,Corners Taken,Tackles,Clearances,Interceptions,Clearances off line,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,2,1076,828,76.9%,1706,60,42,14,49,83,56,NaN,0,10,3,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,0,1565,1223,78.1%,2358,46,68,21,62,98,37,2.0,1,10,6,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,3,1298,1082,83.3%,1873,43,32,16,40,61,59,0.0,1,10,5,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,3,1488,1200,80.6%,2440,58,60,16,86,106,72,1.0,2,29,3,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,0,2066,1803,87.2%,2909,55,76,28,71,76,58,0.0,1,7,5,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,2,2774,2427,87.4%,3761,101,60,35,91,73,69,0.0,1,11,6,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,0,1187,911,76.7%,2016,52,53,10,65,123,87,0.0,1,23,7,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,2,3016,2531,83.9%,4363,75,75,30,98,137,136,1.0,2,18,7,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,0,1556,1381,88.7%,2163,50,49,22,34,41,41,0.0,0,9,5,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,1,1059,852,80.4%,1724,55,39,14,67,87,62,0.0,0,8,3,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,2,1891,1461,77.2%,2958,91,64,41,78,92,86,0.0,2,11,4,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,1,851,606,71.2%,1433,43,18,8,45,78,43,1.0,0,23,9,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,1,1602,1345,83.9%,2278,40,40,21,65,74,58,0.0,0,8,3,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,2,4317,3820,88.4%,5585,69,106,44,122,102,79,0.0,5,8,1,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,1,1192,965,80.9%,1806,44,29,7,56,54,45,0.0,1,12,5,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,2,1276,1043,81.7%,1894,33,26,18,65,97,29,0.0,0,4,4,13,76.5%,48,31,4,5,0,9,9,18

In [110]:
filtered_euro_data = euro_2012_data[["Team","Goals","Yellow Cards","Red Cards"]]
filtered_euro_data

                   Team  Goals  Yellow Cards  Red Cards
0               Croatia      4             9          0
1        Czech Republic      4             7          0
2               Denmark      4             4          0
3               England      5             5          0
4                France      3             6          0
5               Germany     10             4          0
6                Greece      5             9          1
7                 Italy      6            16          0
8           Netherlands      2             5          0
9                Poland      2             7          1
10             Portugal      6            12          0
11  Republic of Ireland      1             6          1
12               Russia      5             6          0
13                Spain     12            11          0
14               Sweden      5             7          0
15              Ukraine      2             5          0

In [111]:
filtered_euro_data["Yellow Cards"]

0      9
1      7
2      4
3      5
4      6
5      4
6      9
7     16
8      5
9      7
10    12
11     6
12     6
13    11
14     7
15     5
Name: Yellow Cards, dtype: int64

### 4.1 Top 5 Yellow Caeds Team

In [112]:
filtered_euro_data.sort_values(by = "Yellow Cards" , ascending = False).head()

        Team  Goals  Yellow Cards  Red Cards
7      Italy      6            16          0
10  Portugal      6            12          0
13     Spain     12            11          0
0    Croatia      4             9          0
6     Greece      5             9          1

### 4.2 List the Teams which has got Red Cards

In [113]:
filtered_euro_data["Red Cards"]

0     0
1     0
2     0
3     0
4     0
5     0
6     1
7     0
8     0
9     1
10    0
11    1
12    0
13    0
14    0
15    0
Name: Red Cards, dtype: int64

In [114]:
filtered_euro_data["Red Cards"] ==  1

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9      True
10    False
11     True
12    False
13    False
14    False
15    False
Name: Red Cards, dtype: bool

In [115]:
filtered_euro_data[filtered_euro_data["Red Cards"] ==  1]

                   Team  Goals  Yellow Cards  Red Cards
6                Greece      5             9          1
9                Poland      2             7          1
11  Republic of Ireland      1             6          1

### 4.3 List the Team which has got more than 8 Yellow Cards

In [116]:
filtered_euro_data["Yellow Cards"] >= 8

0      True
1     False
2     False
3     False
4     False
5     False
6      True
7      True
8     False
9     False
10     True
11    False
12    False
13     True
14    False
15    False
Name: Yellow Cards, dtype: bool

In [117]:
filtered_euro_data[filtered_euro_data["Yellow Cards"] >= 8]

        Team  Goals  Yellow Cards  Red Cards
0    Croatia      4             9          0
6     Greece      5             9          1
7      Italy      6            16          0
10  Portugal      6            12          0
13     Spain     12            11          0

## Chapter 5: How to deal with Missing Values

In [120]:
proitbridge_emp_data = pd.read_csv("employee_data.csv")
proitbridge_emp_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

## Level 1 of Data Cleaning

### Always recommended: I'll call to my client and check with him if he can give the right data - Great!!!

Incase client is asking us to perform the Data cleaning Operations.

#### Step 1: Remove Duplicate entries/records

In [124]:
proitbridge_emp_data.drop_duplicates(inplace = True)   #The complete operations will impact the original dataset
proitbridge_emp_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022

#### Step 2: Find out Null entries

In [129]:
proitbridge_emp_data.shape

(7, 5)

In [125]:
proitbridge_emp_data.isnull()

    Name    Age  Department  Salary  Join_Date
0  False  False       False   False      False
1  False  False       False    True      False
2  False   True       False   False      False
3  False  False       False   False      False
4  False  False       False   False      False
5  False  False       False   False      False
6   True  False       False   False      False

In [126]:
proitbridge_emp_data.isnull().sum()

Name          1
Age           1
Department    0
Salary        1
Join_Date     0
dtype: int64

In [131]:
proitbridge_emp_data.dropna(inplace = True)
proitbridge_emp_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023

In [132]:
proitbridge_emp_data.shape

(4, 5)

#### Step 3: Record in a Document
* Client gave totally 7 Observations out of which 3 entries are removed because those records do not have complete information.

#### Step 4: Get Approval
* send this to client and get the approval to proceed for Model building or Model Training

In [133]:
proitbridge_emp_data.isnull().sum()

Name          0
Age           0
Department    0
Salary        0
Join_Date     0
dtype: int64

## Level 2 of Data Cleaning

In [ ]:
pd.read_excel #You can import multiple excel sheets

In [ ]:
pd.read_csv() #You can import multiple sheets if it's in one CSV file, you need to have seperate CSV files.

In [136]:
pd.read_excel("employee_data.xlsx")

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

In [144]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     - -------------------------------------- 10.2/250.9 kB ? eta -:--:--
     - -------------------------------------- 10.2/250.9 kB ? eta -:--:--
     - -------------------------------------- 10.2/250.9 kB ? eta -:--:--
     - -------------------------------------- 10.2/250.9 kB ? eta -:--:--
     - -------------------------------------- 10.2/250.9 kB ? eta -:--:--
     - -------------------------------------- 10.2/250.9 kB ? eta -:--:--
     --- ---------------------------------- 20.5/250.9 kB 41.0 kB/s eta 0:00:06
     --- ---------------------------------- 20.5/250.9 kB 41.0 kB/s eta 0:00:06
     --- ---------------------------------- 20.5/250.9 kB 41.0 kB/s eta 0:00:06
     ---- --------------------------------- 30.7/250.9 kB 50.4 kB/s eta 0:00:05
     ---- --------------------------------- 30.7/250.9 kB 50.4 kB/s eta 0:00:05
     ---- --------------------------------- 30.7/250.9 kB 50.4 kB/s eta 0:00:05
     ---- --------------------------------- 30.7/250.9 kB 50.4 kB/s eta 0:00:05
     ------ ------------------------------- 41.0/250.9 kB 54.6 kB/s eta 0:00:04
     ------ ------------------------------- 41.0/250.9 kB 54.6 kB/s eta 0:00:04
     ------ ------------------------------- 41.0/250.9 kB 54.6 kB/s eta 0:00:04
     ------ ------------------------------- 41.0/250.9 kB 54.6 kB/s eta 0:00:04
     ------ ------------------------------- 41.0/250.9 kB 54.6 kB/s eta 0:00:04
     ------ ------------------------------- 41.0/250.9 kB 54.6 kB/s eta 0:00:04
     ------ ------------------------------- 41.0/250.9 kB 54.6 kB/s eta 0:00:04
     ------ ------------------------------- 41.0/250.9 kB 54.6 kB/s eta 0:00:04
     ------ ------------------------------- 41.0/250.9 kB 54.6 kB/s eta 0:00:04
     ------ ------------------------------- 41.0/250.9 kB 54.6 kB/s eta 0:00:04
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------- ------------------------------ 51.2/250.9 kB 39.1 kB/s eta 0:00:06
     ------------- ------------------------ 92.2/250.9 kB 36.2 kB/s eta 0:00:05
     ------------- ------------------------ 92.2/250.9 kB 36.2 kB/s eta 0:00:05
     ------------- ------------------------ 92.2/250.9 kB 36.2 kB/s eta 0:00:05
     ------------- ------------------------ 92.2/250.9 kB 36.2 kB/s eta 0:00:05
     ------------- ------------------------ 92.2/250.9 kB 36.2 kB/s eta 0:00:05
     ------------- ------------------------ 92.2/250.9 kB 36.2 kB/s eta 0:00:05
     ------------- ------------------------ 92.2/250.9 kB 36.2 kB/s eta 0:00:05
     ------------- ------------------------ 92.2/250.9 kB 36.2 kB/s eta 0:00:05
     ------------- ------------------------ 92.2/250.9 kB 36.2 kB/s eta 0:00:05
     ------------- ------------------------ 92.2/250.9 kB 36.2 kB/s eta 0:00:05
     ------------- ------------------------ 92.2/250.9 kB 36.2 kB/s eta 0:00:05
     ------------- ------------------------ 92.2/250.9 kB 36.2 kB/s eta 0:00:05
     ------------- ------------------------ 92.2/250.9 kB 36.2 kB/s eta 0:00:05
     ------------- ------------------------ 92.2/250.9 kB 36.2 kB/s eta 0:00:05
     ------------- ------------------------ 92.2/250.9 kB 36.2 kB/s eta 0:00:05
     ------------- ------------------------ 92.2/250.9 kB 36.2 kB/s eta 0:00:05
     ------------- ------------------------ 92.2/250.9 kB 36.2 kB/s eta 0:00:05
     ------------- ------------------------ 92.2/250.9 kB 36.2 kB/s eta 0:00:05
     ------------- ------------------------ 92.2/250.9 kB 36.2 kB/s eta 0:00:05
     ------------- ------------------------ 92.2/250.9 kB 36.2 kB/s eta 0:00:05
     ------------- ------------------------ 92.2/250.9 kB 36.2 kB/s eta 0:00:05
     ------------- ------------------------ 92.2/250.9 kB 36.2 kB/s eta 0:00:05
     ------------------ ------------------ 122.9/250.9 kB 34.0 kB/s eta 0:00:04
     ------------------ ------------------ 122.9/250.9 kB 34.0 kB/s eta 0:00:04
     ------------------ ------------------ 122.9/250.9 kB 34.0 kB/s eta 0:00:04
     ------------------ ------------------ 122.9/250.9 kB 34.0 kB/s eta 0:00:04
     ------------------ ------------------ 122.9/250.9 kB 34.0 kB/s eta 0:00:04
     ------------------ ------------------ 122.9/250.9 kB 34.0 kB/s eta 0:00:04
     ------------------ ------------------ 122.9/250.9 kB 34.0 kB/s eta 0:00:04
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     --------------------- --------------- 143.4/250.9 kB 36.4 kB/s eta 0:00:03
     ------------------------- ----------- 174.1/250.9 kB 29.8 kB/s eta 0:00:03
     ------------------------- ----------- 174.1/250.9 kB 29.8 kB/s eta 0:00:03
     ------------------------- ----------- 174.1/250.9 kB 29.8 kB/s eta 0:00:03
     ------------------------- ----------- 174.1/250.9 kB 29.8 kB/s eta 0:00:03
     ------------------------- ----------- 174.1/250.9 kB 29.8 kB/s eta 0:00:03
     ------------------------- ----------- 174.1/250.9 kB 29.8 kB/s eta 0:00:03
     ------------------------- ----------- 174.1/250.9 kB 29.8 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     --------------------------- --------- 184.3/250.9 kB 29.7 kB/s eta 0:00:03
     ------------------------------ ------ 204.8/250.9 kB 25.9 kB/s eta 0:00:02
     ------------------------------ ------ 204.8/250.9 kB 25.9 kB/s eta 0:00:02
     ------------------------------ ------ 204.8/250.9 kB 25.9 kB/s eta 0:00:02
     ------------------------------ ------ 204.8/250.9 kB 25.9 kB/s eta 0:00:02
     ------------------------------ ------ 204.8/250.9 kB 25.9 kB/s eta 0:00:02
     ------------------------------ ------ 204.8/250.9 kB 25.9 kB/s eta 0:00:02
     ------------------------------ ------ 204.8/250.9 kB 25.9 kB/s eta 0:00:02
     ------------------------------ ------ 204.8/250.9 kB 25.9 kB/s eta 0:00:02
     ------------------------------ ------ 204.8/250.9 kB 25.9 kB/s eta 0:00:02
     ------------------------------ ------ 204.8/250.9 kB 25.9 kB/s eta 0:00:02
     ------------------------------ ------ 204.8/250.9 kB 25.9 kB/s eta 0:00:02
     --------------------------------- --- 225.3/250.9 kB 26.8 kB/s eta 0:00:01
     --------------------------------- --- 225.3/250.9 kB 26.8 kB/s eta 0:00:01
     --------------------------------- --- 225.3/250.9 kB 26.8 kB/s eta 0:00:01
     --------------------------------- --- 225.3/250.9 kB 26.8 kB/s eta 0:00:01
     --------------------------------- --- 225.3/250.9 kB 26.8 kB/s eta 0:00:01
     --------------------------------- --- 225.3/250.9 kB 26.8 kB/s eta 0:00:01
     --------------------------------- --- 225.3/250.9 kB 26.8 kB/s eta 0:00:01
     --------------------------------- --- 225.3/250.9 kB 26.8 kB/s eta 0:00:01
     --------------------------------- --- 225.3/250.9 kB 26.8 kB/s eta 0:00:01
     --------------------------------- --- 225.3/250.9 kB 26.8 kB/s eta 0:00:01
     --------------------------------- --- 225.3/250.9 kB 26.8 kB/s eta 0:00:01
     --------------------------------- --- 225.3/250.9 kB 26.8 kB/s eta 0:00:01
     --------------------------------- --- 225.3/250.9 kB 26.8 kB/s eta 0:00:01
     --------------------------------- --- 225.3/250.9 kB 26.8 kB/s eta 0:00:01
     --------------------------------- --- 225.3/250.9 kB 26.8 kB/s eta 0:00:01
     --------------------------------- --- 225.3/250.9 kB 26.8 kB/s eta 0:00:01
     --------------------------------- --- 225.3/250.9 kB 26.8 kB/s eta 0:00:01
     --------------------------------- --- 225.3/250.9 kB 26.8 kB/s eta 0:00:01
     --------------------------------- --- 225.3/250.9 kB 26.8 kB/s eta 0:00:01
     --------------------------------- --- 225.3/250.9 kB 26.8 kB/s eta 0:00:01
     --------------------------------- --- 225.3/250.9 kB 26.8 kB/s eta 0:00:01
     ---------------------------------- -- 235.5/250.9 kB 25.1 kB/s eta 0:00:01
     ---------------------------------- -- 235.5/250.9 kB 25.1 kB/s eta 0:00:01
     ------------------------------------  245.8/250.9 kB 25.9 kB/s eta 0:00:01
     ------------------------------------- 250.9/250.9 kB 26.3 kB/s eta 0:00:00
Collecting et-xmlfile
  Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [148]:
employee_added_details = pd.read_excel("employee_data.xlsx", sheet_name = "More Employee Data")

In [149]:
employee_added_details

             Name   Age Department   Salary   Join_Date
0          Rajesh  29.0        Ops  60000.0  21-05-2023
1           Nasir  31.0    IT Tech  62000.0  12-11-2020
2         Mathiew   NaN    Support  58000.0  15-01-2025
3         Gilbert  29.0        Ops  60000.0  21-05-2021
4           Kevin  28.0    Support  61000.0  30-07-2024
5           Navin  35.0    Support  72000.0  19-08-2023
6             NaN  40.0    IT Tech  64000.0  10-09-2022
7          Roshan  31.0    IT Tech      NaN  12-11-2020
8       Kuppusamy  28.0        Ops      NaN  21-05-2021
9           Ajesh  28.0    Support      NaN  30-07-2024
10           Diya  31.0    IT Tech  63000.0  12-11-2020
11        Mathiew   NaN    Support  58000.0  15-01-2025
12  Jagadheeswari  28.0    IT Tech      NaN         NaN
13           Mani  28.0        Ops      NaN  21-05-2021

#### Step 1: Drop Duplicates

In [151]:
employee_added_details.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
dtype: bool

In [154]:
employee_added_details.drop_duplicates(inplace = True)

In [155]:
employee_added_details

             Name   Age Department   Salary   Join_Date
0          Rajesh  29.0        Ops  60000.0  21-05-2023
1           Nasir  31.0    IT Tech  62000.0  12-11-2020
2         Mathiew   NaN    Support  58000.0  15-01-2025
3         Gilbert  29.0        Ops  60000.0  21-05-2021
4           Kevin  28.0    Support  61000.0  30-07-2024
5           Navin  35.0    Support  72000.0  19-08-2023
6             NaN  40.0    IT Tech  64000.0  10-09-2022
7          Roshan  31.0    IT Tech      NaN  12-11-2020
8       Kuppusamy  28.0        Ops      NaN  21-05-2021
9           Ajesh  28.0    Support      NaN  30-07-2024
10           Diya  31.0    IT Tech  63000.0  12-11-2020
12  Jagadheeswari  28.0    IT Tech      NaN         NaN
13           Mani  28.0        Ops      NaN  21-05-2021

#### Step 2: Identify Null Entries

In [166]:
employee_added_details.isna().sum()

Name          1
Age           1
Department    0
Salary        5
Join_Date     1
dtype: int64

#### Step 3: Go for best Imputation

In [158]:
print(employee_added_details["Department"].unique())

['Ops' 'IT Tech' 'Support']

In [160]:
employee_added_details["Department"]

0         Ops
1     IT Tech
2     Support
3         Ops
4     Support
5     Support
6     IT Tech
7     IT Tech
8         Ops
9     Support
10    IT Tech
12    IT Tech
13        Ops
Name: Department, dtype: object

In [159]:
employee_added_details["Department"] == "Support"

0     False
1     False
2      True
3     False
4      True
5      True
6     False
7     False
8     False
9      True
10    False
12    False
13    False
Name: Department, dtype: bool

In [161]:
employee_added_details[employee_added_details["Department"] == "Support"]

      Name   Age Department   Salary   Join_Date
2  Mathiew   NaN    Support  58000.0  15-01-2025
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
9    Ajesh  28.0    Support      NaN  30-07-2024

In [163]:
employee_added_details[employee_added_details["Department"] == "IT Tech"]

             Name   Age Department   Salary   Join_Date
1           Nasir  31.0    IT Tech  62000.0  12-11-2020
6             NaN  40.0    IT Tech  64000.0  10-09-2022
7          Roshan  31.0    IT Tech      NaN  12-11-2020
10           Diya  31.0    IT Tech  63000.0  12-11-2020
12  Jagadheeswari  28.0    IT Tech      NaN         NaN

In [164]:
employee_added_details[employee_added_details["Department"] == "Ops"]

         Name   Age Department   Salary   Join_Date
0      Rajesh  29.0        Ops  60000.0  21-05-2023
3     Gilbert  29.0        Ops  60000.0  21-05-2021
8   Kuppusamy  28.0        Ops      NaN  21-05-2021
13       Mani  28.0        Ops      NaN  21-05-2021

In [169]:
employee_added_details[(employee_added_details["Department"] == "Support") & (employee_added_details["Salary"].isna())]

    Name   Age Department  Salary   Join_Date
9  Ajesh  28.0    Support     NaN  30-07-2024