## 1.	Write a program to take a name and age from the user and print a greeting message.

In [11]:
user_name = input("Enter your Name:")
user_age = int(input("Enter your Age:"))

print(f"Hello {user_name}!!! Welcome to Python World. Please check your age, Your age is {user_age}")

Enter your Name: Yujin
Enter your Age: 24

Hello Yujin!!! Welcome to Python World. Please check your age, Your age is 24

## 2.Create a list of numbers and print only even numbers using a for loop.

In [14]:
numbers = range(1,51)
even_numbers = []

for i in numbers:
    if i%2 == 0:
        even_numbers.append(i)
        
print(even_numbers)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]

## 3.Write a program that handles division by zero using try-except.

In [12]:
try:
    num = int(input("Enter Numerator:"))
    den = int(input("Enter Denominator:"))

    result = num/den
    print(result)
except ZeroDivisionError:
        print("Invalid Entry! Enter a Number other than 0")
except ValueError:
        print("Invalid Entry! Enter a Number not character")

Enter Numerator: 23
Enter Denominator: 0

Invalid Entry! Enter a Number other than 0

## 4.Given a string, count how many vowels it has.

In [28]:
user_input = input("Enter a word or sentence:")
count = 0

for i in user_input.lower():
    if i in "aeiou":
        count+=1

print("Total number of vowels:",count)

Enter a word or sentence: Yujin Malini

Total number of vowels: 5

## 5.Reverse a list without using built-in functions.

In [30]:
original_list = [1,2,3,4,5]
original_list.reverse()
original_list

[5, 4, 3, 2, 1]

In [34]:
original_list = [1,2,3,4,5]
reverse_list = []
i = len(original_list) - 1

while i>=0:
    reverse_list.append(original_list[i])
    i = i-1

print(reverse_list)

[5, 4, 3, 2, 1]

## 6.Create a dictionary with at least 5 key-value pairs and print them.

In [37]:
math_students_mark = {"Name":["Yujin","Malini","Love","Valentine"],"Maths":[67,89,100,34],"Science":[100,90,80,70]}
print(math_students_mark)

{'Name': ['Yujin', 'Malini', 'Love', 'Valentine'], 'Maths': [67, 89, 100, 34], 'Science': [100, 90, 80, 70]}

In [2]:
import pandas as pd

learners_data = pd.DataFrame({"Name":["Yujin","Malini","Love","Valentine" ,"Raju" ,"Swetha","Selva"],"Age": [24,21,25,30,43,45,23],
                             "Maths":[67,89,100,34,45,34,23],"Science":[100,90,80,70,43,34,56],"Tamil":[90,100,75,60,56,67,67], 
                             "Location":["Chennai","Bangalore","Trichy","Salem","Chennai","Erode","dindugal"]})
learners_data

        Name  Age  Maths  Science  Tamil   Location
0      Yujin   24     67      100     90    Chennai
1     Malini   21     89       90    100  Bangalore
2       Love   25    100       80     75     Trichy
3  Valentine   30     34       70     60      Salem
4       Raju   43     45       43     56    Chennai
5     Swetha   45     34       34     67      Erode
6      Selva   23     23       56     67   dindugal

In [57]:
learners_data.to_csv(path_or_buf = "learners_data.csv")  #to change a dataFrame into cSV file

## 7.Write a Pandas code to read a CSV and print the top 5 rows.

In [59]:
pd.read_csv("learners_data.csv").head()

   Unnamed: 0       Name  Age  Maths  Science  Tamil   Location
0           0      Yujin   24     67      100     90    Chennai
1           1     Malini   21     89       90    100  Bangalore
2           2       Love   25    100       80     75     Trichy
3           3  Valentine   30     34       70     60      Salem
4           4       Raju   43     45       43     56    Chennai

## 8.Create a DataFrame from a Python dictionary.

In [60]:
learners_data = pd.DataFrame({"Name":["Yujin","Malini","Love","Valentine" ,"Raju" ,"Swetha","Selva"],"Age": [24,21,25,30,43,45,23],
                             "Maths":[67,89,100,34,45,34,23],"Science":[100,90,80,70,43,34,56],"Tamil":[90,100,75,60,56,67,67], 
                             "Location":["Chennai","Bangalore","Trichy","Salem","Chennai","Erode","dindugal"]})
learners_data

        Name  Age  Maths  Science  Tamil   Location
0      Yujin   24     67      100     90    Chennai
1     Malini   21     89       90    100  Bangalore
2       Love   25    100       80     75     Trichy
3  Valentine   30     34       70     60      Salem
4       Raju   43     45       43     56    Chennai
5     Swetha   45     34       34     67      Erode
6      Selva   23     23       56     67   dindugal

## 9.	Replace all missing values in a DataFrame with the column’s mean.

In [4]:
employee_data = pd.read_csv("employee_data.csv")
employee_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

In [5]:
employee_data["Salary"]

0    60000.0
1        NaN
2    58000.0
3    60000.0
4    61000.0
5    72000.0
6    64000.0
7        NaN
Name: Salary, dtype: float64

In [6]:
employee_data["Salary"].mean()

np.float64(62500.0)

In [ ]:
employee_data.fillna()

In [14]:
employee_data["Salary"].fillna(value = employee_data["Salary"].mean(),   inplace = True)
employee_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech  62500.0  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech  62500.0  12-11-2020

## 10.Filter rows in a DataFrame where the "Age" column is greater than 30

In [18]:
employee_data["Age"] > 30

0    False
1     True
2    False
3    False
4    False
5     True
6     True
7     True
Name: Age, dtype: bool

In [17]:
employee_data[employee_data["Age"] > 30]

    Name   Age Department   Salary   Join_Date
1  Nasir  31.0    IT Tech  62500.0  12-11-2020
5  Navin  35.0    Support  72000.0  19-08-2023
6    NaN  40.0         IT  64000.0  10-09-2022
7  Nasir  31.0    IT Tech  62500.0  12-11-2020