# Task 1

## Create 1 Example for each functions of all Data Structures

### 1. List
* List accepts duplicate values
* We add list in One diminsional (1D)
* It is Heterogeneous - can use int , float , str
* Indexing and slicing is possible
* Mutable - Values can be assigned to a variable can changed anytime in the future

In [18]:
home_appliances = ["Chair","Table","TV","AC","Cot"]
home_appliances

['Chair', 'Table', 'TV', 'AC', 'Cot']

In [19]:
type(home_appliances )

list

#### 1. append - It add values in the list at the end

In [23]:
home_appliances.append("Fridge")   #Here how many times when you run the cell, it add the product again and again to the list even when you delete the product
home_appliances

['Chair', 'Table', 'TV', 'AC', 'Cot', 'Sofa', 'Sofa', 'Fridge']

#### 2. clear - It removes all items from the list

In [25]:
home_appliances.clear()   
home_appliances

[]

#### 3. copy - Return a shallow copy of the list

In [30]:
home_appliances = ["Chair","Table","TV","AC","Cot"]
home_appliances.copy()

['Chair', 'Table', 'TV', 'AC', 'Cot']

#### 4. count - Return number of occurrences of value

In [31]:
home_appliances.count("Chair")

1

In [32]:
home_appliances = ["Chair","Table","TV","AC","Cot","Chair"]
home_appliances.count("Chair")

2

#### 5. extend - Extend list by appending elements from the iterable

In [54]:
home_appliances = ["Chair","Table","TV","AC","Cot"]
home_appliances.extend([1, 90, 100.00, "Fridge"])
print(home_appliances)

['Chair', 'Table', 'TV', 'AC', 'Cot', 1, 90, 100.0, 'Fridge']

#### 6. index - Return first index of value
Raises valueError if value not found.

In [56]:
home_appliances = ["Chair","Table","TV","AC","Cot"]
home_appliances.index("TV")

2

In [85]:
home_appliances = ["Chair","Table","TV","AC","Cot","TV"]
home_appliances.index("TV",0,3)

2

In [59]:
home_appliances = ["Chair","Table","TV","AC","Cot","TV"]
home_appliances.index("TV",0,2)

ValueError: 'TV' is not in list

#### 7. insert - Insert object before index

In [65]:
home_appliances = ["Chair","Table","TV","AC","Cot"]
home_appliances.insert(2,"Fridge")
home_appliances

['Chair', 'Table', 'Fridge', 'TV', 'AC', 'Cot']

#### 8. pop - Remove and return item at index (default last)

Raises IndexError if list is empty or index is out of range.

In [71]:
home_appliances = ["Chair","Table","TV","AC","Cot"]
print(home_appliances.pop(2))
home_appliances

TV

['Chair', 'Table', 'AC', 'Cot']

In [68]:
home_appliances = ["Chair","Table","TV","AC","Cot"]
home_appliances.pop(5)
home_appliances

IndexError: pop index out of range

#### 9. remove - Remove first occurrence of value.

Raises ValueError if the value is not present.

In [163]:
home_appliances = ["Chair","Table","TV","AC","Cot","Cot"]
home_appliances.remove("Cot")
home_appliances

['Chair', 'Table', 'TV', 'AC', 'Cot']

#### 10. reverse - Reverse *IN PLACE*

In [74]:
home_appliances = ["Chair","Table","TV","AC","Cot"]
home_appliances.reverse()
home_appliances

['Cot', 'AC', 'TV', 'Table', 'Chair']

#### 11. sort - Sort the list in ascending order and return None.

The sort is in-place (i.e. the list itself is modified) and stable (i.e. the
order of two equal elements is maintained).

If a key function is given, apply it once to each list item and sort them,
ascending or descending, according to their function values.

The reverse flag can be set to sort in descending order.

In [75]:
home_appliances = ["Chair","Table","TV","AC","Cot"]
home_appliances.sort()
home_appliances

['AC', 'Chair', 'Cot', 'TV', 'Table']

In [83]:
home_appliances = ["Chair","Table","TV","AC","Cot"]
home_appliances.sort(reverse=True)
home_appliances

['Table', 'TV', 'Cot', 'Chair', 'AC']

In [84]:
home_appliances = ["Chair","Table","TV","AC","Cot"]
home_appliances[0:3]

['Chair', 'Table', 'TV']

##### =========================================================================================

### 2. Sets
* Set is One dimensional (1D)
* It is heterogeneous
* Set won't allow duplicate values
* Indexing and Slicing is not possible
* Set is mutable

In [87]:
home_appliances = set()
type(home_appliances)

set

In [100]:
home_appliances = {"Chair","Table","TV","AC","Cot","Chair"}  #No duplicate values
home_appliances

{'AC', 'Chair', 'Cot', 'TV', 'Table'}

#### 1. add - Add an element to a set.

This has no effect if the element is already present.

In [94]:
home_appliances = {"Chair","Table","TV","AC","Cot"}  #Set always arrange the element in ascending order like alphabets and numerics
home_appliances.add("Fridge")
home_appliances

{'AC', 'Chair', 'Cot', 'Fridge', 'TV', 'Table'}

#### 2. clear - Remove all elements from this set.

In [95]:
home_appliances = {"Chair","Table","TV","AC","Cot"}
home_appliances.clear()
home_appliances

set()

#### 3. copy - Return a shallow copy of a set.

In [96]:
home_appliances = {"Chair","Table","TV","AC","Cot"}
home_appliances.copy()
home_appliances

{'AC', 'Chair', 'Cot', 'TV', 'Table'}

#### 4. difference - Return the difference of two or more sets as a new set.

(i.e. all elements that are in this set but not the others.)

In [102]:
home_appliances = {"Chair","Table","TV","AC","Cot"}
home_appliances_1 = {"Chair","Table","TV","AC"}
print(home_appliances.difference(home_appliances_1))
#home_appliances

{'Cot'}

#### 5. difference_update -  Remove common elements from the original set(it updates the set itself)

In [107]:
home_appliances = {"Chair","Table","TV","AC","Cot"}
home_appliances_1 = {"Chair","Table"}
home_appliances.difference_update(home_appliances_1)
print(home_appliances)

{'AC', 'Cot', 'TV'}

#### 6. discard - Remove an element from a set if it is a member.

If the element is not a member, do nothing.

In [111]:
home_appliances = {"Chair","Table","TV","AC","Cot"}
home_appliances.discard("AC")
home_appliances

{'Chair', 'Cot', 'TV', 'Table'}

In [112]:
home_appliances = {"Chair","Table","TV","AC","Cot"}
home_appliances.discard("Fridge")
home_appliances

{'AC', 'Chair', 'Cot', 'TV', 'Table'}

#### 7. intersection - Return the intersection of two sets as a new set.

(i.e. all elements that are in both sets.)

In [115]:
home_appliances = {"Chair","Table","TV","AC","Cot"}
home_appliances_1 = {"Chair","Table","Frige","Sofa","TV"}
home_appliances.intersection(home_appliances_1)
#home_appliances

{'Chair', 'TV', 'Table'}

#### 8. intersection_update - Update a set with the intersection of itself and another.

In [119]:
home_appliances = {"Chair","Table","TV","AC","Cot"}
home_appliances_1 = {"Chair","Table","Frige","Sofa","TV"}
home_appliances.intersection_update(home_appliances_1)
print(home_appliances)
home_appliances_1.intersection_update(home_appliances)
print(home_appliances_1)

{'Chair', 'Table', 'TV'}
{'Table', 'Chair', 'TV'}

#### 9. isdisjoint - Return True if two sets have a no common elements

In [120]:
home_appliances = {"Chair","Table","TV","AC","Cot"}
home_appliances_1 = {"Chair","Table","Frige","Sofa","TV"}
home_appliances.isdisjoint(home_appliances_1)

False

In [121]:
home_appliances = {"Chair","Table","TV","AC","Cot"}
home_appliances_1 = {"Sofa","Washing Machine","Fan","Mixer",45, 34, 23}
home_appliances.isdisjoint(home_appliances_1)

True

#### 10. issubset - Report whether another set contains this set.
Check Is set1 inside set2 ?
* Smaller -> Bigger

In [122]:
home_appliances = {"Chair","Table","TV","AC","Cot"}
home_appliances_1 = {"Sofa","Washing Machine","Fan","Mixer",45, 34, 23}
home_appliances.issubset(home_appliances_1)

False

In [125]:
home_appliances = {"Chair","Table","TV","AC","Cot"}   #Here the total home_appliances set is completely present in the second set
home_appliances_1 = {"Chair","Table","Frige","Sofa","TV","AC","Cot"}
home_appliances.issubset(home_appliances_1)

True

#### 11. issuperset - Report whether this set contains another set
Check Does set1 contain set2?
* Bigger -> Smaller

In [129]:
home_appliances = {"Chair","Table","TV","AC","Cot"}
home_appliances_1 = {"Fridge","sofa","Table","TV"}
home_appliances.issuperset(home_appliances_1)

False

In [130]:
home_appliances = {"Chair","Table","TV","AC","Cot"}   #Here the total home_appliances set is completely present in the second set so the second set is a superset
home_appliances_1 = {"Chair","Table","Frige","Sofa","TV","AC","Cot"}
home_appliances_1.issuperset(home_appliances)

True

#### 12. pop - Remove and return an arbitrary set element.
Raises KeyError if the set is empty.

* pop() in set remove any one element randomly
* pop() only no argument should pass inside the function

In [140]:
home_appliances = {"Chair","Table","TV","AC","Cot"}
print(home_appliances)
print(home_appliances.pop())
home_appliances

{'Table', 'AC', 'Cot', 'Chair', 'TV'}
Table

{'AC', 'Chair', 'Cot', 'TV'}

#### 13. remove - Remove an element from a set; it must be a member.

If the element is not a member, raise a KeyError.

In [143]:
home_appliances = {"Chair","Table","TV","AC","Cot"}
home_appliances.remove("AC")
home_appliances

{'Chair', 'Cot', 'TV', 'Table'}

In [144]:
home_appliances = {"Chair","Table","TV","AC","Cot"}
home_appliances.remove("Fridge")
home_appliances

KeyError: 'Fridge'

#### 14. symmetric_difference - Remove common elements, and print a new set by combining the unique elements from two sets

In [147]:
home_appliances = {"Chair","Table","TV","AC","Cot","Washing machine","Fan"}
home_appliances_1 = {"Chair","Table","Frige","Sofa","TV","AC","Cot"}
home_appliances.symmetric_difference(home_appliances_1)

{'Fan', 'Frige', 'Sofa', 'Washing machine'}

In [150]:
set_1 = {1,2,3}        
set_2 = {3,4,5}
set_1.symmetric_difference(set_2)

{1, 2, 4, 5}

#### 15. symmetric_difference_update - Update a set with the symmetric difference of itself and another

* Removes common elements
* keeps non-common elements
* Returns a new set(symmetric_difference)
* Updaates it to a original set(symmetric_difference_update)

In [152]:
set_1 = {1,2,3}        
set_2 = {3,4,5}
set_1.symmetric_difference_update(set_2)
set_1

{1, 2, 4, 5}

In [153]:
home_appliances = {"Chair","Table","TV","AC","Cot","Washing machine","Fan"}
home_appliances_1 = {"Chair","Table","Frige","Sofa","TV","AC","Cot"}
home_appliances.symmetric_difference_update(home_appliances_1)
home_appliances

{'Fan', 'Frige', 'Sofa', 'Washing machine'}

#### 16. union - Return the union of sets as a new set.
when combine remove duplicates

In [154]:
home_appliances = {"Chair","Table","TV","AC","Cot","Washing machine","Fan"}
home_appliances_1 = {"Chair","Table","Frige","Sofa","TV","AC","Cot"}
home_appliances.union(home_appliances_1)

{'AC',
 'Chair',
 'Cot',
 'Fan',
 'Frige',
 'Sofa',
 'TV',
 'Table',
 'Washing machine'}

In [155]:
set_1 = {1,2,3}        
set_2 = {3,4,5}
set_1.union(set_2)

{1, 2, 3, 4, 5}

#### 17. update - Update a set with the union of itself and others

In [161]:
home_appliances = {"Chair","Table","TV","AC","Cot","Washing machine","Fan"}
home_appliances_1 = {"Chair","Table","Frige","Sofa","TV","AC","Cot"}
home_appliances.update(home_appliances_1)
home_appliances

{'AC',
 'Chair',
 'Cot',
 'Fan',
 'Frige',
 'Sofa',
 'TV',
 'Table',
 'Washing machine'}

##### ==============================================================================================

### 3. Tuple
* Tuple is one dimensional
* It is heterogeneous
* Tuple allows duplicate values
* Indexing and slicing is possible
* Tuple is Immutable

In [165]:
home_appliances = ()
home_appliances

()

In [166]:
type(home_appliances)

tuple

In [169]:
home_appliances = ("Chair","Table","TV","AC","Cot","Chair")  #duplicate values
home_appliances

('Chair', 'Table', 'TV', 'AC', 'Cot', 'Chair')

#### 1. count - Return number of occurrences of value

In [170]:
home_appliances = ("Chair","Table","TV","AC","Cot","Chair")  
home_appliances.count("Chair")

2

#### 2. index - Return first index of value.

Raises ValueError if the value is not present.

In [182]:
home_appliances = ("Chair","Table","TV","AC","Cot","Chair")  
home_appliances.index("Table")

1

In [173]:
home_appliances = ("Chair","Table","TV","AC","Cot","TV","Chair")   #Using indexing and slicing
home_appliances.index("TV",1,6)

2

In [181]:
home_appliances = ("Chair","Table","TV","AC","Cot","TV","Chair")   #Using indexing and slicing
home_appliances.index("TV",3,6)

5

##### ===========================================================================================

### 4. Dictionary
It is called as a Key:Value Pair

* Dict is Two dimensional (2D)
* It is heterogeneous
* Indexing and Slicing is not possible
* Don't create duplicate key , But you can create duplicate values

In [183]:
home_appliances = {}
home_appliances

{}

In [184]:
type(home_appliances)

dict

In [187]:
home_appliances = {"TV":35000 , "AC":45000, "Washing machine":50000, "Fan":1500}
home_appliances

{'TV': 35000, 'AC': 45000, 'Washing machine': 50000, 'Fan': 1500}

#### 1. clear - Remove all items from Dict

In [189]:
home_appliances = {"TV":35000 , "AC":45000, "Washing machine":50000, "Fan":1500}
home_appliances.clear()
home_appliances

{}

#### 2. copy - A shallow copy of Dict

In [190]:
home_appliances = {"TV":35000 , "AC":45000, "Washing machine":50000, "Fan":1500}
home_appliances.copy()
home_appliances

{'TV': 35000, 'AC': 45000, 'Washing machine': 50000, 'Fan': 1500}

#### 3. fromkeys - Create a new dictionary with given keys and a same value assigned to all keys

In [196]:
home_appliances = {"TV", "AC", "Washing machine", "Fan"}
home = dict.fromkeys(home_appliances,90000)
home

{'AC': 90000, 'Fan': 90000, 'Washing machine': 90000, 'TV': 90000}

In [198]:
home_appliances = {"TV":35000 , "AC":45000, "Washing machine":50000, "Fan":1500}  #Here already values are assigned eventhough the values are reassigned to all values using this function
home_appliances.fromkeys(home_appliances,90000)

{'TV': 90000, 'AC': 90000, 'Washing machine': 90000, 'Fan': 90000}

#### 4. get - Return the value for key if key is in the dictionary, else default.

In [200]:
home_appliances = {"TV":35000 , "AC":45000, "Washing machine":50000, "Fan":1500}
home_appliances.get("Fan")

1500

In [223]:
home_appliances = {"TV":35000 , "AC":[90000,45000], "Washing machine":50000, "Fan":1500}
home_appliances.get("AC")

[90000, 45000]

#### 5. items -  A set-like object providing a view on Dict's items

In [208]:
home_appliances = {"TV":35000 , "AC":45000, "Washing machine":50000, "Fan":1500}
home_appliances.items()

dict_items([('TV', 35000), ('AC', 45000), ('Washing machine', 50000), ('Fan', 1500)])

#### 6. keys - A set-like object providing a view on Dict's keys

In [209]:
home_appliances = {"TV":35000 , "AC":45000, "Washing machine":50000, "Fan":1500}
home_appliances.keys()

dict_keys(['TV', 'AC', 'Washing machine', 'Fan'])

#### 7. pop - Remove specified key and return the corresponding value.

If the key is not found, return the default if given; otherwise,
raise a KeyError.

In [211]:
home_appliances = {"TV":35000 , "AC":45000, "Washing machine":50000, "Fan":1500}
home_appliances.pop("TV")

35000

In [212]:
home_appliances

{'AC': 45000, 'Washing machine': 50000, 'Fan': 1500}

In [222]:
home_appliances = {"TV":[40,35000], "AC":45000, "Washing machine":50000, "Fan":1500}
home_appliances.pop("TV")

[40, 35000]

#### 8. popitem - Remove and return a (key, value) pair as a 2-tuple.

* Pairs are returned in LIFO (last-in, first-out) order.
* Raises KeyError if the dict is empty.

In [225]:
home_appliances = {"TV":35000 , "AC":45000, "Washing machine":50000, "Fan":1500}
home_appliances.popitem()

('Fan', 1500)

In [227]:
home_appliances

{'TV': 35000, 'AC': 45000, 'Washing machine': 50000}

In [228]:
home_appliances.popitem()

('Washing machine', 50000)

In [229]:
home_appliances

{'TV': 35000, 'AC': 45000}

#### 9. setdefault - Insert key with a value of default if key is not in the dictionary.

Return the value for key if key is in the dictionary, else default

In [231]:
home_appliances = {"TV":35000 , "AC":45000,  "Fan":1500}
home_appliances.setdefault("Washing machine",80000)

80000

In [232]:
home_appliances

{'TV': 35000, 'AC': 45000, 'Fan': 1500, 'Washing machine': 80000}

In [230]:
home_appliances = {"TV":35000 , "AC":45000, "Washing machine":50000, "Fan":1500}
home_appliances.setdefault("Washing machine",80000)

50000

In [233]:
home_appliances

{'TV': 35000, 'AC': 45000, 'Fan': 1500, 'Washing machine': 80000}

#### 10. update - Add or change multiple key value pairs at once

In [238]:
home_appliances = {"TV":35000 , "AC":45000, "Washing machine":50000, "Fan":1500}  #Value update
home_appliances.update({"AC":50})
home_appliances

{'TV': 35000, 'AC': 50, 'Washing machine': 50000, 'Fan': 1500}

In [241]:
home_appliances = {"TV":35000 , "AC":45000, "Washing machine":50000, "Fan":1500} #New key value pair update - inserted
home_appliances.update({"Fridge":25000})
home_appliances

{'TV': 35000,
 'AC': 45000,
 'Washing machine': 50000,
 'Fan': 1500,
 'Fridge': 25000}

In [242]:
home_appliances = {"TV":35000 , "AC":45000, "Washing machine":50000, "Fan":1500} #Multiple key value pairs inserted
home_appliances.update({"Fridge":25000, "Mixer":3000})
home_appliances

{'TV': 35000,
 'AC': 45000,
 'Washing machine': 50000,
 'Fan': 1500,
 'Fridge': 25000,
 'Mixer': 3000}

In [245]:
home_appliances = {"TV":35000 , "AC":45000, "Washing machine":50000, "Fan":1500}
home_appliances_1 = {"Fridge":25000, "Mixer":3000}
home_appliances.update(home_appliances_1)
home_appliances

{'TV': 35000,
 'AC': 45000,
 'Washing machine': 50000,
 'Fan': 1500,
 'Fridge': 25000,
 'Mixer': 3000}

#### 11. values - An object providing a view on Dict's values

In [247]:
home_appliances = {"TV":35000 , "AC":45000, "Washing machine":50000, "Fan":1500}  #Value update
home_appliances.values()

dict_values([35000, 45000, 50000, 1500])

# Task 2

## Create 3 Dataframes using Dictionaries

### DataFrame 1 - Sales & Customer Dataset

In [249]:
import pandas as pd

customer_datas = {"Order Id":[1,2,3,4,5,6,7], "Name":["Malini","Yujin","Jerrin","Valentine","Anu","Jesus","Kishore"] ,
                  "Place":["Bangalore","Bangalore","Chennai","Mumbai","Kerala","Odisha","Hyderabad"] , 
                  "Product":["Laptop","Mobile","Headphones","Airdopes","Tablet","Speaker","Charger"] ,
                  "Price":[50000,20000,1000,1500,30000,2000,1500] , 
                  "Quantity":[1,2,3,2,1,2,2] , "Status":["Paid","Paid","Pending","Paid","Pending","Paid","Pending"]}

pd.DataFrame(data=customer_datas)

   Order Id       Name      Place     Product  Price  Quantity   Status
0         1     Malini  Bangalore      Laptop  50000         1     Paid
1         2      Yujin  Bangalore      Mobile  20000         2     Paid
2         3     Jerrin    Chennai  Headphones   1000         3  Pending
3         4  Valentine     Mumbai    Airdopes   1500         2     Paid
4         5        Anu     Kerala      Tablet  30000         1  Pending
5         6      Jesus     Odisha     Speaker   2000         2     Paid
6         7    Kishore  Hyderabad     Charger   1500         2  Pending

### DataFrame 2 - Employee Performance Dataset

In [250]:
import pandas as pd

employee_data = {"Emp_Id":[101,102,103,104,105,106,107,108,109,110] , "Name":["Malini","Yujin","Love","Valentine","Lara","Jacob","Joseph","Sarah","Abraham","Isaac"],
                 "Department":["IT","HR","Marketing","IT","HR","Marketing","IT","HR","Marketing","IT"] , 
                 "Role":["Developer","Manager","Executive","Tester","Executive","Manager","Developer","Manager","Executive","Developer"],
                 "Salary":[450000, 500000 , 600000, 450000, 600000, 500000, 500000, 450000, 600000, 550000],
                 "Rating":[4.5 , 5, 3, 4, 4, 5, 5, 3.2, 4.2,5],
                 "Experience":[2,3,1,4,5,3,4,4,2.5,1.5]}

pd.DataFrame(data=employee_data)

   Emp_Id       Name Department       Role  Salary  Rating  Experience
0     101     Malini         IT  Developer  450000     4.5         2.0
1     102      Yujin         HR    Manager  500000     5.0         3.0
2     103       Love  Marketing  Executive  600000     3.0         1.0
3     104  Valentine         IT     Tester  450000     4.0         4.0
4     105       Lara         HR  Executive  600000     4.0         5.0
5     106      Jacob  Marketing    Manager  500000     5.0         3.0
6     107     Joseph         IT  Developer  500000     5.0         4.0
7     108      Sarah         HR    Manager  450000     3.2         4.0
8     109    Abraham  Marketing  Executive  600000     4.2         2.5
9     110      Isaac         IT  Developer  550000     5.0         1.5

### DataFrame 3 - Cricket Player Dataset

In [253]:
import pandas as pd

player_datas = {"Player_Id":[1001,1002,1003,1004,1005,1006,1007,1008,1009,1010] ,
                "Name":["MS Dhoni","Virat Kohli", "Rohit sharma","Ruturaj Gaikwad","Devon Conway", "Ajinkya Rahane","Ravindra Jadeja","Shivam Dube","Deepak Chahar","Maheesh Deekshana"],
                "Country":["India","India","India","India","New Zealand","India","India","India","India","SriLanka"] ,
                "Role":["WicketKeeper-Batsman","Batsman","Batsman","Batsman","Batsman","Batsman","All-rounder","All-rounder","Bowler","Bowler"],
                "Matches":[250,274,243,52,23,158,226,51,72,25],
                "Runs":[5082,12898,9837,1797,924,4400,2692,1106,80,35]}

pd.DataFrame(data=player_datas)

,Player_Id,Name,Country,Role,Matches,Runs
0,1001,MS Dhoni,India,WicketKeeper-Batsman,250,5082
1,1002,Virat Kohli,India,Batsman,274,12898
2,1003,Rohit sharma,India,Batsman,243,9837
3,1004,Ruturaj Gaikwad,India,Batsman,52,1797
4,1005,Devon Conway,New Zealand,Batsman,23,924
5,1006,Ajinkya Rahane,India,Batsman,158,4400
6,1007,Ravindra Jadeja,India,All-rounder,226,2692
7,1008,Shivam Dube,India,All-rounder,51,1106
8,1009,Deepak Chahar,India,Bowler,72,80
9,1010,Maheesh Deekshana,SriLanka,Bowler,25,35