# Task 1

## Data Cleaning Challenge on Sales Data

In [163]:
import pandas as pd

In [164]:
sales_data_2017 = pd.read_csv("Sales Transactions-2017.csv")
sales_date_2018 = pd.read_csv("Sales Transactions-2018.csv")
sales_data_2019 = pd.read_csv("Sales Transactions-2019.csv")

In [165]:
sales_data_2017

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
47285,31/03/2018,Sal:10042,Vkp,10*10 SHEET,25,137,"3,425.00",NaN,"3,425.00"
47286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47288,NaN,Total,NaN,NaN,"607,734.60","669,300.49","9,953,816.13","106,607.00","9,868,583.13"
47289,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71"

In [166]:
sales_date_2018

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2018,Sal:146,TP13,SILVER POUCH 9*12,50,85,"4,250.00",NaN,"66,724.00"
1,1/4/2018,Sal:146,TP13,RUBBER,5,290,"1,450.00",NaN,NaN
2,1/4/2018,Sal:146,TP13,DURGA 10*12 Blue,"1,600.00",5.5,"8,800.00",NaN,NaN
3,1/4/2018,Sal:146,TP13,DURGA 13*16 BLUE,400,11,"4,400.00",NaN,NaN
4,1/4/2018,Sal:146,TP13,10*12 SARAS-NAT,600,8.1,"4,860.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
44735,31/03/2019,Sal:9610,HAMPI FOODS,SPOON SOOFY,200,40,"8,000.00",NaN,NaN
44736,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44738,NaN,Total,NaN,NaN,"666,056.00","1,067,808.80","10,796,991.30","29,999.00","10,787,647.30"
44739,NaN,Total,NaN,NaN,"7,097,803.00","10,024,197.00","117,897,671.80","720,204.00","117,427,983.80"

In [167]:
sales_data_2019

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2019,Sal:687,BALAJI PLASTICS,DONA-VAI-9100,1,"1,730.00","1,730.00",NaN,"3,460.00"
1,1/4/2019,Sal:687,BALAJI PLASTICS,SMART BOUL(48),1,"1,730.00","1,730.00",NaN,NaN
2,1/4/2019,Sal:688,BALAJI PLASTICS,Vishnu Ice,110,18.5,"2,035.00",NaN,"2,035.00"
3,,,28/3,,0,0,,,
4,1/4/2019,Sal:689,BALAJI PLASTICS,100LEAF -SP,3,585,"1,755.00",NaN,"1,755.00"
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

### Target Dataset

In [168]:
sales_data_edited = pd.read_csv("Sales-Transactions-Edited.csv")
sales_data_edited

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
95557,12/9/2019,4265,TP13,SPOON MED M.W,20,11.0
95558,12/9/2019,4266,K.SRIHARI,SMART BOUL(48),1,1830.0
95559,12/9/2019,4267,SMS,SMARTBOUL GLA(4000),1,1520.0
95560,12/9/2019,4268,ANILFANCY,RR WINEGLASS,100,20.0
95561,12/9/2019,4268,ANILFANCY,RR WATER GLASS,100,20.0

In [169]:
sales_data_edited.isna().sum()

Date       0
Voucher    0
Party      0
Product    0
Qty        0
Rate       1
dtype: int64

In [170]:
sales_data_edited.dtypes

Date        object
Voucher      int64
Party       object
Product     object
Qty          int64
Rate       float64
dtype: object

### 1. Perform Initial Analysis

#### Step 1: Concat the 3 Sales files

In [171]:
sales_full_data = pd.concat([sales_data_2017,sales_date_2018,sales_data_2019], ignore_index=False)
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

#### Step 2: Find the rows and columns for the full dataset

In [172]:
sales_full_data.shape

(111206, 9)

#### Step 3: Checking and listing the Null values in each column

In [173]:
sales_full_data.isna().sum()

Date               12591
Voucher            12557
Party                 40
Product            12591
Qty                12557
Rate               12558
Gross              12558
Disc              105609
Voucher Amount     83646
dtype: int64

#### Step 4: Finding the data types for each column

In [174]:
sales_full_data.dtypes

Date              object
Voucher           object
Party             object
Product           object
Qty               object
Rate              object
Gross             object
Disc              object
Voucher Amount    object
dtype: object

#### Step 5: Using Describe function

In [175]:
sales_full_data.describe(include = "all")

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
count,98615,98649,111166,98615,98649,98648,98648,5597,27560
unique,836,10044,1994,867,546,1109,2548,371,7149
top,,,TP13,,100,,,,
freq,3053,3053,13056,3053,12528,3051,3053,3053,3053

#### Step 6: Finding the unique values in each column

In [176]:
sales_full_data.nunique()

Date                836
Voucher           10044
Party              1994
Product             867
Qty                 546
Rate               1109
Gross              2548
Disc                371
Voucher Amount     7149
dtype: int64

### 2. Data Cleaning

#### Step 1: Drop the unwanted columns

In [177]:
sales_full_data = sales_full_data.drop(columns = ["Gross","Disc","Voucher Amount"])
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00"
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00"
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00"
...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16
19172,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40"

#### Step 2: Remove the null values in every column

In [178]:
sales_full_data = sales_full_data.dropna(subset = ["Date","Voucher","Party","Product","Qty","Rate"])
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00"
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00"
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00"
...,...,...,...,...,...,...
19167,10/10/2019,Sal:4935,K.SRIHARI,16*20(100-W),140,26
19168,10/10/2019,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4
19169,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16
19170,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800,8.5
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16

#### Step 3: Check the Total observations and features

In [179]:
sales_full_data.shape

(98614, 6)

#### Step 4: Modifications in Voucher column

In [182]:
sales_full_data["Voucher"] = sales_full_data["Voucher"].astype(str).str.replace('Sal:','').str.strip() #Converting the Voucher Object into string and replace the Sal: into empty spaces also strip the entire value
sales_full_data = sales_full_data[sales_full_data["Voucher"] != '']  #If Voucher is not equal to empty spaces it should sliced and updated in the dataset.
sales_full_data["Voucher"] = sales_full_data["Voucher"].astype(int)  #The Voucher should converted from string to integer

In [183]:
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00"
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00"
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00"
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00"
...,...,...,...,...,...,...
19167,10/10/2019,4935,K.SRIHARI,16*20(100-W),140,26
19168,10/10/2019,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4
19169,10/10/2019,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16
19170,10/10/2019,4935,K.SRIHARI,10*12 RK,800,8.5
19171,10/10/2019,4935,K.SRIHARI,13*16 WHITE RK,400,16

In [184]:
sales_full_data.dtypes

Date       object
Voucher     int64
Party      object
Product    object
Qty        object
Rate       object
dtype: object

In [185]:
sales_full_data["Voucher"].isna().sum()

np.int64(0)

#### Step 5: Modifications in Rate column

In [186]:
sales_full_data["Rate"] = sales_full_data["Rate"].astype(str).str.replace(',','') #Converting the rate from object to string datatype and replace the , into no space
sales_full_data["Rate"] = pd.to_numeric(sales_full_data["Rate"], errors='coerce') #Convert the string into numeric

In [187]:
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
19167,10/10/2019,4935,K.SRIHARI,16*20(100-W),140,26.0
19168,10/10/2019,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4
19169,10/10/2019,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0
19170,10/10/2019,4935,K.SRIHARI,10*12 RK,800,8.5
19171,10/10/2019,4935,K.SRIHARI,13*16 WHITE RK,400,16.0

In [188]:
sales_full_data.dtypes

Date        object
Voucher      int64
Party       object
Product     object
Qty         object
Rate       float64
dtype: object

In [189]:
sales_full_data["Rate"].isna().sum()

np.int64(0)

#### Step 6: Modifications in Qty column

In [193]:
sales_full_data["Qty"] = sales_full_data["Qty"].astype(str).str.replace(',','') #Convert object into string and replace (,) into empty space
sales_full_data["Qty"] = pd.to_numeric(sales_full_data["Qty"])
sales_full_data["Qty"] = sales_full_data["Qty"].astype(int)                     #Convert string into int

In [194]:
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
19167,10/10/2019,4935,K.SRIHARI,16*20(100-W),140,26.0
19168,10/10/2019,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4
19169,10/10/2019,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0
19170,10/10/2019,4935,K.SRIHARI,10*12 RK,800,8.5
19171,10/10/2019,4935,K.SRIHARI,13*16 WHITE RK,400,16.0

In [195]:
sales_full_data.dtypes

Date        object
Voucher      int64
Party       object
Product     object
Qty          int64
Rate       float64
dtype: object

In [196]:
sales_full_data["Qty"].isna().sum()

np.int64(0)

#### Step 7: Reset the index

In [197]:
sales_full_data = sales_full_data.reset_index(drop=True)
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
95556,10/10/2019,4935,K.SRIHARI,16*20(100-W),140,26.0
95557,10/10/2019,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4
95558,10/10/2019,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0
95559,10/10/2019,4935,K.SRIHARI,10*12 RK,800,8.5
95560,10/10/2019,4935,K.SRIHARI,13*16 WHITE RK,400,16.0

#### Step 8: Change the Date column from object to Datetime dtype

In [198]:
sales_full_data["Date"] = pd.to_datetime(sales_full_data["Date"] , dayfirst=True)
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate
0,2017-04-01,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,2017-04-01,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,2017-04-01,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,2017-04-01,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,2017-04-01,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
95556,2019-10-10,4935,K.SRIHARI,16*20(100-W),140,26.0
95557,2019-10-10,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4
95558,2019-10-10,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0
95559,2019-10-10,4935,K.SRIHARI,10*12 RK,800,8.5
95560,2019-10-10,4935,K.SRIHARI,13*16 WHITE RK,400,16.0

In [59]:
sales_full_data.shape

(95561, 6)

In [199]:
sales_full_data.dtypes

Date       datetime64[ns]
Voucher             int64
Party              object
Product            object
Qty                 int64
Rate              float64
dtype: object

### Final Dataset after performing Data Cleaning

In [200]:
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate
0,2017-04-01,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,2017-04-01,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,2017-04-01,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,2017-04-01,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,2017-04-01,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
95556,2019-10-10,4935,K.SRIHARI,16*20(100-W),140,26.0
95557,2019-10-10,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4
95558,2019-10-10,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0
95559,2019-10-10,4935,K.SRIHARI,10*12 RK,800,8.5
95560,2019-10-10,4935,K.SRIHARI,13*16 WHITE RK,400,16.0

In [201]:
sales_full_data.isna().sum()

Date       0
Voucher    0
Party      0
Product    0
Qty        0
Rate       0
dtype: int64

In [202]:
sales_full_data.dtypes

Date       datetime64[ns]
Voucher             int64
Party              object
Product            object
Qty                 int64
Rate              float64
dtype: object

In [217]:
sales_full_data.to_csv("Sales_cleaned_data.csv")

## Some Meaningful insights

In [2]:
import pandas as pd

sales_cleaned_data = pd.read_csv("Sales_cleaned_data.csv")

### Top 10 Product sold in 3 years

In [4]:
sales_cleaned_data.groupby(by = "Product")["Qty"].sum().sort_values(ascending=False).head(10)

Product
14 GREEN               3474510
CYCLE-BLU-10*12         741675
500ML PLASTIC BOULS     587600
DURGA 10*12 Blue        530384
10*12 SARAS-NAT         433630
CYCLE-BK-10*12          431060
Vishnu 250ml            400239
ROBO 10*12              353880
10*12 KRISHNA-BK(10     349720
TIRUMALA-50(13*16)      346776
Name: Qty, dtype: int64

In [25]:
sales_cleaned_data.groupby(by = "Product")["Rate"].sum().sort_values(ascending=False).head(10)

Product
Loose Items            5260552.95
DONA-VAI-9100          2431747.00
GST AMOUNT             2013879.92
LITE FOAM(1200)        1928930.00
SILV-CONT-750ML(100    1499175.01
SILV-CONT-450ML(150     697745.00
SMART BOUL(48)          598095.00
Gold Leaf Sitting       501725.00
CLASSIC ENJOY(750)      430135.00
DONA-1100               385664.00
Name: Rate, dtype: float64

### Top 20 Products sold least in 3 years

In [6]:
sales_cleaned_data.groupby(by = "Product")["Qty"].sum().sort_values().head(20)

Product
SUPER CLASSIC          0
TOOTH PICS-;PLASTIC    1
NON WOVEN 16*20 -CL    1
TRANSPORT CHARGES      1
OWN ITEM               1
MAAZA TETRA            1
ROPE-SUPER             1
RAJA BOUL(5250)        1
SILV CONT-(660)        1
FOM-PRINT(50*120)      1
LOCK COVER             1
VENIGAR                1
CLING FILM 600MTS      1
7"ESSFOAM(2250)        1
6" Therm(5600)         1
NAPKEENS PRINT 33*3    1
10*15 SPECIAL D-CUT    1
PLASTIC BOULS -LOOS    2
L.d Colour Kg          2
TAMBOOLAM COVER        2
Name: Qty, dtype: int64

### Which Party has sold many products across 3 years

In [8]:
sales_cleaned_data.groupby("Party")["Qty"].sum().sort_values(ascending=False).head(10)

Party
TP13               1890661
SEKHAR MARKET      1147801
K.SRIHARI           889709
KPR                 675614
SUNDHA PLASTICS     516056
SVP-BUCHHI          512105
HAMPI FOODS         403982
GANESHMESS          310173
DSP-SEKHAR          299734
SLST-GDR            291971
Name: Qty, dtype: int64

In [24]:
sales_cleaned_data.groupby("Party")["Rate"].sum().sort_values(ascending=False).head(10)

Party
K.SRIHARI              3992850.48
TP13                   2360956.83
HAMPI FOODS            1610018.49
KHAN AND KHAN PLAST     808110.77
SUNDHA PLASTICS         707006.63
BALAJI PLASTICS         668905.10
Srinu                   586613.15
KPR                     541321.65
SHAAR CANTEEN           512267.91
BSR                     343919.98
Name: Rate, dtype: float64

### Which Party has sold least products across 3 years

In [9]:
sales_cleaned_data.groupby("Party")["Qty"].sum().sort_values().head(10)

Party
MALLI-RENIGUNTA        1
KANYAKAPARAMESWARI     1
DHARALU                1
N1 ENTERPRISES         2
BHUVANESWARI           2
CH PRAVEEN-KVL         4
RAVI POLYPACK          4
DVV SATYANARAYANA-K    5
PACS KODURPADU         6
BALAJI PLASTICS-ONG    8
Name: Qty, dtype: int64

#### Pull up the quantity based on party and product

In [18]:
sales_cleaned_data.groupby(["Party","Product"])["Qty"].sum().sort_values(ascending =False).head(10)

Party            Product
SEKHAR MARKET    14 GREEN               984195
K.SRIHARI        14 GREEN               334320
TP13             DURGA 10*12 Blue       303350
SUNDHA PLASTICS  LIDS-750ML             250000
GANESHMESS       500ML PLASTIC BOULS    183600
SLST-GDR         14 GREEN               182080
HAMPI FOODS      SWEET BOX-500GRAMS     166750
SVP-BUCHHI       14 GREEN               155800
TP13             10*12 SARAS-NAT        144640
SUNDHA PLASTICS  LIDS-450ML             126000
Name: Qty, dtype: int64

In [23]:
sales_cleaned_data.groupby(["Party","Product"])["Qty"].sum().sort_values().head(10)

Party                Product
SESHAMMA-ALR PETA    SUPER CLASSIC          0
VENKATESWARA PROVIS  ZEN-REALPACK           0
                     ZEND-PREMIUM           0
YVSR-VGIRI           SPOON SOOFY            1
PRATHAP-NELLORE      100LEAF -SP            1
K.VENUGOPAL-RAPUR    Loose Items            1
PRATHAP-NELLORE      SILV-CONT-250ML(200    1
Y.SIDHYYA-TALUPURU   NO-3                   1
YUVARAJ PLASTICS-AN  10RS RUBBER SHEET      1
Y.SIDHYYA-TALUPURU   HIGH COUNTING BLUE     1
Name: Qty, dtype: int64

### Pull up the rate based on Party and Product

In [27]:
sales_cleaned_data.groupby(["Party","Product"])["Rate"].sum().sort_values(ascending =False).head(20)

Party                Product
K.SRIHARI            Loose Items            3468770.00
HAMPI FOODS          GST AMOUNT             1240327.66
KHAN AND KHAN PLAST  Loose Items             595360.00
SHAAR CANTEEN        GST AMOUNT              410598.16
TP13                 LITE FOAM(1200)         311040.00
                     CLASSIC ENJOY(750)      276240.00
BALAJI PLASTICS      DONA-VAI-9100           258300.00
TP13                 SILV-CONT-750ML(100     257050.00
                     DONA-VAI-9100           242280.00
SEKHAR MARKET        Loose Items             220255.00
KRISHNA AYYAPAGUDI   Loose Items             217499.00
KRISHNAPATNAM PORT   GST AMOUNT              203499.51
BALAJI PLASTICS      LITE FOAM(1200)         196680.00
TP13                 Loose Items             154178.55
Srinu                DONA-VAI-9100           143590.00
BSCPL INFRASTRUCTUR  GST AMOUNT              140132.10
SUNDHA PLASTICS      LITE FOAM(1200)         138660.00
                     DONA-1100               120770.00
                     SILV-CONT-750ML(100     116330.01
Srinu                SILV-CONT-450ML(150     100150.00
Name: Rate, dtype: float64

In [28]:
sales_cleaned_data.groupby(["Party","Product"])["Rate"].sum().sort_values().head(20)

Party                Product
K.SRIHARI            LIDS-450ML        0.01
SUNDHA PLASTICS      LIDS-250ML        0.03
                     LIDS-450ML        0.08
KPR                  LIDS-750ML        0.10
SUNDHA PLASTICS      LIDS-750 MW       0.12
TP13                 LIDS-250ML        0.20
BALAJI PLASTICS      LIDS-250ML        0.20
                     LIDS-450ML        0.25
KNC                  LIDS-450ML        0.25
K.SRIHARI            LIDS-250ML        0.26
RAILWAY CUSTOMER     LIDS-450ML        0.30
KK TRADERS           LIDS-450ML        0.30
SUNDHA PLASTICS      LIDS-450MW        0.33
NAGABUSHANAM-CHEJAR  ROLLS             0.34
BALAJI PLASTICS      LIDS-750ML        0.35
Sms                  LIDS-750ML        0.40
A1 PLASTICS-SPT      LIDS-750ML        0.40
RAVIKANTH GDR        LIDS-750ML        0.40
MOHAN CHOUDARY-INAM  LIDS-750ML        0.40
MAYURI CATERING      5*5 DONA LOOSE    0.55
Name: Rate, dtype: float64

In [15]:
sales_cleaned_data.groupby(by=["Party","Product"])["Rate"].agg(func = ["mean","min","max","sum"])

                                       mean     min     max     sum
Party           Product
A.BHASKER-VGIRI 14 GREEN             35.000    35.0    35.0    35.0
                GARUDA 10*12 BLUE     7.000     7.0     7.0     7.0
                GARUDA 13*16 BLUE    13.000    13.0    13.0    13.0
                LITE FOAM(1200)    1680.000  1680.0  1680.0  1680.0
                N0-5                145.000   145.0   145.0   145.0
...                                     ...     ...     ...     ...
YVT-PMR         NO-00               140.000   140.0   140.0   140.0
                NO-1                144.000   140.0   148.0   288.0
                NO-2                144.000   140.0   148.0   288.0
                Tirumala Kirana     154.000   154.0   154.0   154.0
                Vishnu 250ml         28.625    28.0    30.0   114.5

[19726 rows x 4 columns]

In [21]:
sales_cleaned_data.groupby(by=["Party","Product"])["Qty"].agg(func = ["mean","min","max","sum"])

                                    mean  min  max  sum
Party           Product
A.BHASKER-VGIRI 14 GREEN            40.0   40   40   40
                GARUDA 10*12 BLUE  100.0  100  100  100
                GARUDA 13*16 BLUE  100.0  100  100  100
                LITE FOAM(1200)      1.0    1    1    1
                N0-5                 3.0    3    3    3
...                                  ...  ...  ...  ...
YVT-PMR         NO-00                5.0    5    5    5
                NO-1                 5.0    5    5   10
                NO-2                 5.0    5    5   10
                Tirumala Kirana     43.0   43   43   43
                Vishnu 250ml       150.0  100  200  600

[19726 rows x 4 columns]

# Task 2 

## Merge Function

In [30]:
import pandas as pd

In [37]:
orders_data = pd.read_csv("orders.csv")
orders_data

   Order_ID Customer_ID   Product  Qty  Order_Date
0       101         C01    Laptop    1  2024-01-01
1       102         C02     Phone    2  2024-01-02
2       103         C03    Tablet    1  2024-01-03
3       104         C04   Monitor    3  2024-01-04
4       105         C05  Keyboard    5  2024-01-05
5       106         C01     Mouse    2  2024-01-06
6       107         C03    Laptop    1  2024-01-07
7       108         C06     Phone    1  2024-01-08

In [38]:
customers_data = pd.read_csv("customers.csv")
customers_data

  Customer_ID    Name       City    Segment
0         C01  Malini    Chennai     Retail
1         C02    Ravi     Mumbai  Wholesale
2         C03   Priya      Delhi     Retail
3         C04   Karan       Pune  Wholesale
4         C07   Sneha  Hyderabad     Retail
5         C08   Arjun  Bangalore     Retail

### Inner join

Keeps only customers that exist in both datasets
* co1,co2,co3,co4 matched
* co5,co6 dropped(not in customers)
* co7,co8 dropped(not in orders)
* co1 and co3 appear twice because they placed 2 orders each

Result 6 rows

In [48]:
inner_join = pd.merge(orders_data,customers_data, on="Customer_ID" , how="inner")
inner_join

   Order_ID Customer_ID  Product  Qty  Order_Date    Name     City    Segment
0       101         C01   Laptop    1  2024-01-01  Malini  Chennai     Retail
1       102         C02    Phone    2  2024-01-02    Ravi   Mumbai  Wholesale
2       103         C03   Tablet    1  2024-01-03   Priya    Delhi     Retail
3       104         C04  Monitor    3  2024-01-04   Karan     Pune  Wholesale
4       106         C01    Mouse    2  2024-01-06  Malini  Chennai     Retail
5       107         C03   Laptop    1  2024-01-07   Priya    Delhi     Retail

### Left join 

All of left(orders) match from right(customers)

* Keeps all 8 rows from orders(left table) no matter what
* Matches customer info where available
* co5 -> no match in customers -> Name,City,Segment = NaN
* co6 -> no match in customers -> Name,City,Segment = NaN
* co7, co8 dropped (We can only care about orders here)

Result 8 rows

In [46]:
left_join = pd.merge(orders_data,customers_data, on="Customer_ID" , how="left")
left_join

   Order_ID Customer_ID   Product  Qty  Order_Date    Name     City    Segment
0       101         C01    Laptop    1  2024-01-01  Malini  Chennai     Retail
1       102         C02     Phone    2  2024-01-02    Ravi   Mumbai  Wholesale
2       103         C03    Tablet    1  2024-01-03   Priya    Delhi     Retail
3       104         C04   Monitor    3  2024-01-04   Karan     Pune  Wholesale
4       105         C05  Keyboard    5  2024-01-05     NaN      NaN        NaN
5       106         C01     Mouse    2  2024-01-06  Malini  Chennai     Retail
6       107         C03    Laptop    1  2024-01-07   Priya    Delhi     Retail
7       108         C06     Phone    1  2024-01-08     NaN      NaN        NaN

### Right join

All of right(Customers), match from eft(orders)

* Keeps all 6 rows from customers(right table) no matter what
* Matches order info where available
* co7 -> no orders palced -> Order_ID,Product,Qty = NaN
* co8 -> no orders palced -> Order_ID,Product,Qty = NaN
* co5, co6 dropped(not in customers)

Result 8 rows

In [50]:
right_join = pd.merge(orders_data,customers_data, on=None, how="right")
right_join

,Order_ID,Customer_ID,Product,Qty,Order_Date,Name,City,Segment
0,101.0,C01,Laptop,1.0,2024-01-01,Malini,Chennai,Retail
1,106.0,C01,Mouse,2.0,2024-01-06,Malini,Chennai,Retail
2,102.0,C02,Phone,2.0,2024-01-02,Ravi,Mumbai,Wholesale
3,103.0,C03,Tablet,1.0,2024-01-03,Priya,Delhi,Retail
4,107.0,C03,Laptop,1.0,2024-01-07,Priya,Delhi,Retail
5,104.0,C04,Monitor,3.0,2024-01-04,Karan,Pune,Wholesale
6,NaN,C07,NaN,NaN,NaN,Sneha,Hyderabad,Retail
7,NaN,C08,NaN,NaN,NaN,Arjun,Bangalore,Retail

### Outer join

Everything from both tables

* Keeps all rows from both tables
* co1,co2,co3,co4 -> Matched full info
* co5,co6 -> only in orders -> Customer info = NaN
* co7,co8 -> only in customers -> order info = NaN

Result 10 rows (largest of all joins)

In [52]:
outer_join = pd.merge(orders_data,customers_data, on=None, how="outer")
outer_join

,Order_ID,Customer_ID,Product,Qty,Order_Date,Name,City,Segment
0,101.0,C01,Laptop,1.0,2024-01-01,Malini,Chennai,Retail
1,106.0,C01,Mouse,2.0,2024-01-06,Malini,Chennai,Retail
2,102.0,C02,Phone,2.0,2024-01-02,Ravi,Mumbai,Wholesale
3,103.0,C03,Tablet,1.0,2024-01-03,Priya,Delhi,Retail
4,107.0,C03,Laptop,1.0,2024-01-07,Priya,Delhi,Retail
5,104.0,C04,Monitor,3.0,2024-01-04,Karan,Pune,Wholesale
6,105.0,C05,Keyboard,5.0,2024-01-05,NaN,NaN,NaN
7,108.0,C06,Phone,1.0,2024-01-08,NaN,NaN,NaN
8,NaN,C07,NaN,NaN,NaN,Sneha,Hyderabad,Retail
9,NaN,C08,NaN,NaN,NaN,Arjun,Bangalore,Retail

# Task 3

## List Comprehension

In [53]:
import pandas as pd

In [57]:
orders_data = pd.read_csv("orders.csv")
orders_data

   Order_ID Customer_ID   Product  Qty  Order_Date
0       101         C01    Laptop    1  2024-01-01
1       102         C02     Phone    2  2024-01-02
2       103         C03    Tablet    1  2024-01-03
3       104         C04   Monitor    3  2024-01-04
4       105         C05  Keyboard    5  2024-01-05
5       106         C01     Mouse    2  2024-01-06
6       107         C03    Laptop    1  2024-01-07
7       108         C06     Phone    1  2024-01-08

In [58]:
customers_data = pd.read_csv("customers.csv")
customers_data

  Customer_ID    Name       City    Segment
0         C01  Malini    Chennai     Retail
1         C02    Ravi     Mumbai  Wholesale
2         C03   Priya      Delhi     Retail
3         C04   Karan       Pune  Wholesale
4         C07   Sneha  Hyderabad     Retail
5         C08   Arjun  Bangalore     Retail

### Ex 1: Extract all Product names from orders as a list

In [56]:
products = [p for p in orders_data["Product"]]
products

['Laptop',
 'Phone',
 'Tablet',
 'Monitor',
 'Keyboard',
 'Mouse',
 'Laptop',
 'Phone']

### Ex 2: Get all unique city names from orders as a list

In [59]:
cities = [c for c in customers_data["City"].unique()]
cities

['Chennai', 'Mumbai', 'Delhi', 'Pune', 'Hyderabad', 'Bangalore']

### Ex 3: UpperCase all Customers name

In [60]:
upper_names = [n.upper() for n in customers_data["Name"]]
upper_names

['MALINI', 'RAVI', 'PRIYA', 'KARAN', 'SNEHA', 'ARJUN']

### Ex 4: Get all Order_IDs as a list

In [62]:
order_ids = [o for o in orders_data["Order_ID"]]
order_ids

[101, 102, 103, 104, 105, 106, 107, 108]

### Ex 5: Filter products where Qty > 1

In [65]:
high_qty_products = [p for p in orders_data["Product"] if orders_data.loc[orders_data["Product"] == p, "Qty"].values[0]>1]
high_qty_products

['Phone', 'Monitor', 'Keyboard', 'Mouse', 'Phone']

### Ex 6: Get Customers from retail segment only

In [66]:
retail_customers = [n for n in customers_data["Name"] if customers_data.loc[customers_data["Name"] == n ,"Segment"].values[0] == "Retail"]
retail_customers

['Malini', 'Priya', 'Sneha', 'Arjun']

### Ex 7: Label each order as "Bulk" if Qty >= 3 else "Regular"

In [72]:
orders_data["Order_Type"] = ["Bulk" if q >= 3 else "Regular" for q in orders_data["Qty"]]
orders_data[["Order_ID", "Product", "Qty","Order_Type"]]

   Order_ID   Product  Qty Order_Type
0       101    Laptop    1    Regular
1       102     Phone    2    Regular
2       103    Tablet    1    Regular
3       104   Monitor    3       Bulk
4       105  Keyboard    5       Bulk
5       106     Mouse    2    Regular
6       107    Laptop    1    Regular
7       108     Phone    1    Regular

### Ex 8: Find Customer_IDs that are in orders but not in customers

In [73]:
registered = [c for c in customers_data["Customer_ID"]]
unregistered = [c for c in orders_data["Customer_ID"] if c not in registered]
unregistered

['C05', 'C06']

# Task 4 

## Lambda Function

In [2]:
import pandas as pd

In [3]:
orders = pd.read_csv("orders.csv")
orders

   Order_ID Customer_ID   Product  Qty  Order_Date
0       101         C01    Laptop    1  2024-01-01
1       102         C02     Phone    2  2024-01-02
2       103         C03    Tablet    1  2024-01-03
3       104         C04   Monitor    3  2024-01-04
4       105         C05  Keyboard    5  2024-01-05
5       106         C01     Mouse    2  2024-01-06
6       107         C03    Laptop    1  2024-01-07
7       108         C06     Phone    1  2024-01-08

In [4]:
customers = pd.read_csv("customers.csv")
customers

  Customer_ID    Name       City    Segment
0         C01  Malini    Chennai     Retail
1         C02    Ravi     Mumbai  Wholesale
2         C03   Priya      Delhi     Retail
3         C04   Karan       Pune  Wholesale
4         C07   Sneha  Hyderabad     Retail
5         C08   Arjun  Bangalore     Retail

### Lambda Function using apply function

In [115]:
orders["Order_Type"] = orders["Qty"].apply(lambda x: "Bulk" if x>= 3 else "regular")
orders[["Product" , "Qty", "Order_Type"]]

    Product  Qty Order_Type
0    Laptop    1    regular
1     Phone    2    regular
2    Tablet    1    regular
3   Monitor    3       Bulk
4  Keyboard    5       Bulk
5     Mouse    2    regular
6    Laptop    1    regular
7     Phone    1    regular

In [116]:
orders

   Order_ID Customer_ID   Product  Qty  Order_Date Order_Type
0       101         C01    Laptop    1  2024-01-01    regular
1       102         C02     Phone    2  2024-01-02    regular
2       103         C03    Tablet    1  2024-01-03    regular
3       104         C04   Monitor    3  2024-01-04       Bulk
4       105         C05  Keyboard    5  2024-01-05       Bulk
5       106         C01     Mouse    2  2024-01-06    regular
6       107         C03    Laptop    1  2024-01-07    regular
7       108         C06     Phone    1  2024-01-08    regular

### Lambda function using map in apply to the dataset

* Map applies a function to every element in a list and returns a new list of the same size.

Syntax:

list(map(lambda x: expression, list))

#### Ex 1:

In [124]:
registered_ids = list(customers["Customer_ID"])
orders["Is_Registered"] = list(map(lambda x: "Registered" if x in registered_ids else "Unregistered", orders["Customer_ID"]))
orders[["Customer_ID", "Is_Registered"]]

  Customer_ID Is_Registered
0         C01    Registered
1         C02    Registered
2         C03    Registered
3         C04    Registered
4         C05  Unregistered
5         C01    Registered
6         C03    Registered
7         C06  Unregistered

In [125]:
orders

   Order_ID Customer_ID   Product  Qty  Order_Date Order_Type Is_Registered
0       101         C01    Laptop    1  2024-01-01    regular    Registered
1       102         C02     Phone    2  2024-01-02    regular    Registered
2       103         C03    Tablet    1  2024-01-03    regular    Registered
3       104         C04   Monitor    3  2024-01-04       Bulk    Registered
4       105         C05  Keyboard    5  2024-01-05       Bulk  Unregistered
5       106         C01     Mouse    2  2024-01-06    regular    Registered
6       107         C03    Laptop    1  2024-01-07    regular    Registered
7       108         C06     Phone    1  2024-01-08    regular  Unregistered

#### Ex 2:

In [134]:
metro_cities = ["Chennai", "Mumbai", "Delhi" , "Bangalore"]
customers["City_Type"] = list(map(lambda x: "Metro" if x in metro_cities else "Non-Metro" , customers["City"]))
customers["Priority"] = customers["City_Type"].apply(lambda x: "High priority" if x == "Metro" else "Normal Priority")
customers[["City","City_Type" ,"Priority"]]

        City  City_Type         Priority
0    Chennai      Metro    High priority
1     Mumbai      Metro    High priority
2      Delhi      Metro    High priority
3       Pune  Non-Metro  Normal Priority
4  Hyderabad  Non-Metro  Normal Priority
5  Bangalore      Metro    High priority

In [135]:
customers

  Customer_ID    Name       City    Segment  City_Type         Priority
0         C01  Malini    Chennai     Retail      Metro    High priority
1         C02    Ravi     Mumbai  Wholesale      Metro    High priority
2         C03   Priya      Delhi     Retail      Metro    High priority
3         C04   Karan       Pune  Wholesale  Non-Metro  Normal Priority
4         C07   Sneha  Hyderabad     Retail  Non-Metro  Normal Priority
5         C08   Arjun  Bangalore     Retail      Metro    High priority

### Lambda function using Filter in apply to the dataset

* filter picks only the elements that satisfy a condition and returns a smaller list

Syntax

list(filter(lambda x: condition, list))

#### Ex 1:

In [13]:
order_cust_list = list(orders["Customer_ID"])
customers["Order_Count"] = customers["Customer_ID"].apply(lambda x: len(list(filter(lambda o:o == x, order_cust_list))))
customers[["Name","Order_Count"]]

     Name  Order_Count
0  Malini            2
1    Ravi            1
2   Priya            2
3   Karan            1
4   Sneha            0
5   Arjun            0

In [14]:
customers

  Customer_ID    Name       City    Segment  Order_Count
0         C01  Malini    Chennai     Retail            2
1         C02    Ravi     Mumbai  Wholesale            1
2         C03   Priya      Delhi     Retail            2
3         C04   Karan       Pune  Wholesale            1
4         C07   Sneha  Hyderabad     Retail            0
5         C08   Arjun  Bangalore     Retail            0

#### Ex 2:

In [16]:
customers["Has_Order"] = customers["Customer_ID"].apply(lambda x: "Yes" if list(filter(lambda o:o == x, order_cust_list)) else "No")
customers[["Name","Has_Order"]]

     Name Has_Order
0  Malini       Yes
1    Ravi       Yes
2   Priya       Yes
3   Karan       Yes
4   Sneha        No
5   Arjun        No

In [17]:
customers

  Customer_ID    Name       City    Segment  Order_Count Has_Order
0         C01  Malini    Chennai     Retail            2       Yes
1         C02    Ravi     Mumbai  Wholesale            1       Yes
2         C03   Priya      Delhi     Retail            2       Yes
3         C04   Karan       Pune  Wholesale            1       Yes
4         C07   Sneha  Hyderabad     Retail            0        No
5         C08   Arjun  Bangalore     Retail            0        No

### Lambda using Reduce function in apply to the dataset

* Reduce combines all elements into a single value by applying a function repeatedly.

Syntax:

from functools import reduce
reduce(lambda a , b: expression, list)

#### Ex 1:

In [23]:
import pandas as pd
from functools import reduce

In [24]:
qty_cust_list = list(zip(orders["Customer_ID"], orders["Qty"]))
customers["Total_Qty"] = customers["Customer_ID"].apply(lambda x: reduce(lambda a, b: a+b, 
                                        [q for c, q in qty_cust_list if c == x])
                                    if [q for c , q in qty_cust_list if c==x] else 0)
customers[["Name","Total_Qty"]]

     Name  Total_Qty
0  Malini          3
1    Ravi          2
2   Priya          2
3   Karan          3
4   Sneha          0
5   Arjun          0

In [25]:
customers

  Customer_ID    Name       City    Segment  Order_Count Has_Order  Total_Qty
0         C01  Malini    Chennai     Retail            2       Yes          3
1         C02    Ravi     Mumbai  Wholesale            1       Yes          2
2         C03   Priya      Delhi     Retail            2       Yes          2
3         C04   Karan       Pune  Wholesale            1       Yes          3
4         C07   Sneha  Hyderabad     Retail            0        No          0
5         C08   Arjun  Bangalore     Retail            0        No          0

#### Ex 2:

In [29]:
customers["Max_Qty"] = customers["Customer_ID"].apply(lambda x: reduce(lambda a, b: a if a> b else b, 
                                                [q for c, q in qty_cust_list if c == x])
                                            if[q for c, q in qty_cust_list if c==x] else 0)
customers[["Name","Max_Qty"]]

     Name  Max_Qty
0  Malini        2
1    Ravi        2
2   Priya        1
3   Karan        3
4   Sneha        0
5   Arjun        0

In [30]:
customers

,Customer_ID,Name,City,Segment,Order_Count,Has_Order,Total_Qty,Max_Qty
0,C01,Malini,Chennai,Retail,2,Yes,3,2
1,C02,Ravi,Mumbai,Wholesale,1,Yes,2,2
2,C03,Priya,Delhi,Retail,2,Yes,2,1
3,C04,Karan,Pune,Wholesale,1,Yes,3,3
4,C07,Sneha,Hyderabad,Retail,0,No,0,0
5,C08,Arjun,Bangalore,Retail,0,No,0,0