## Why Python Built-In Data Structures?
* To collect multiple data in a structure

#### 4 Data Structures in Python
1. List
2. Sets
3. Tuples
4. Dictionary - Key & Value

# 1. List

* List accepts duplicate values
* We add list in One diminsional (1D)
* It is Heterogeneous - can use int , float , str
* Indexing and slicing is possible
* Mutable - Values can be assigned to a variable can changed anytime in the future

In [1]:
67,78,10,100,80

(67, 78, 10, 100, 80)

In [3]:
students_mark = 67,78,10,100,80
students_mark

(67, 78, 10, 100, 80)

In [4]:
type(students_mark)

tuple

##### Actual List

In [5]:
empty_cart = []
empty_cart

[]

In [6]:
type(empty_cart)

list

In [9]:
items_to_buy = ["Apple","Banana","Mango","Grapes"]
items_to_buy

['Apple', 'Banana', 'Mango', 'Grapes']

In [10]:
type(items_to_buy)

list

In [15]:
items_to_buy = ["Apple","Banana","Mango","Grapes","Apple", 8, 9.54, 10]
items_to_buy

['Apple', 'Banana', 'Mango', 'Grapes', 'Apple', 8, 9.54, 10]

In [16]:
len(items_to_buy)

8

In [20]:
items_to_buy[2]  #Indexing - Positive Indexing starts from 0  (Which means starts from left to right)

'Mango'

In [19]:
items_to_buy[-4]  #Indexing from Negative Indexing starts from -1 (Which means starts from right to left)

'Apple'

In [21]:
items_to_buy[0:3]

['Apple', 'Banana', 'Mango']

In [22]:
items_to_buy[:3]

['Apple', 'Banana', 'Mango']

In [24]:
items_to_buy[2:7]

['Mango', 'Grapes', 'Apple', 8, 9.54]

In [25]:
items_to_buy[-6:-3]

['Mango', 'Grapes', 'Apple']

In [26]:
items_to_buy[1] = "Watermelon"

In [27]:
items_to_buy

['Apple', 'Watermelon', 'Mango', 'Grapes', 'Apple', 8, 9.54, 10]

In [38]:
items_to_buy.append("Red Banana")
items_to_buy

['Apple', 'Watermelon', 'Mango', 'Grapes', 'Apple', 8, 9.54, 10, 'Red Banana']

# 2. Sets

* Set is One dimensional (1D)
* It is heterogeneous
* Set won't allow duplicate values
* Indexing and Slicing is not possible
* Set is mutable

In [28]:
empty_cart_2 = set()

In [29]:
empty_cart_2

set()

In [30]:
type(empty_cart_2)

set

In [31]:
items_to_buy_2 = {"Apple","Banana","Mango","Grapes","Apple", 8, 9.54, 10}
items_to_buy_2

{10, 8, 9.54, 'Apple', 'Banana', 'Grapes', 'Mango'}

In [32]:
type(items_to_buy_2)

set

In [33]:
items_to_buy_2[3]

TypeError: 'set' object is not subscriptable

In [34]:
items_to_buy_2[0:5]

TypeError: 'set' object is not subscriptable

In [35]:
items_to_buy_2.add("sapota")
items_to_buy_2

{10, 8, 9.54, 'Apple', 'Banana', 'Grapes', 'Mango', 'sapota'}

In [37]:
items_to_buy_2.discard("Apple")
items_to_buy_2

{10, 8, 9.54, 'Banana', 'Grapes', 'Mango', 'sapota'}

# 3. Tuple

* Tuple is one dimensional
* It is heterogeneous
* Tuple allows duplicate values
* Indexing and slicing is possible
* Tuple is Immutable

In [40]:
empty_cart_3 = ()
empty_cart_3

()

In [41]:
type(empty_cart_3)

tuple

In [42]:
items_to_buy_3 = ("Apple","Banana","Mango","Grapes","Apple", 8, 9.54, 10)
items_to_buy_3

('Apple', 'Banana', 'Mango', 'Grapes', 'Apple', 8, 9.54, 10)

In [43]:
items_to_buy_3[0:3]

('Apple', 'Banana', 'Mango')

In [45]:
items_to_buy_3[0] = "Orange"

TypeError: 'str' object does not support item assignment

In [53]:
items_to_buy_3 = ("Apple","Banana","Mango","Grapes","Apple", 8, 9.54, 10)
items_to_buy_3

('Apple', 'Banana', 'Mango', 'Grapes', 'Apple', 8, 9.54, 10)

In [51]:
items_to_buy_3.count("Apple")

0

In [54]:
items_to_buy_3.index("Banana")

1

# 4. Dictionary

It is called as a Key:Value Pair

* Dict is Two dimensional (2D)
* It is heterogeneous
* Indexing and Slicing is not possible
* Don't create duplicate key , But you can create duplicate values

In [55]:
empty_cart_4 = {}
empty_cart_4

{}

In [56]:
type(empty_cart_4)

dict

In [57]:
student_mark = {"Tamil":98,
                "English":89,
                "Maths":100}

In [58]:
type(empty_cart_4)

dict

In [59]:
items_to_buy_4  = {"Potato":3, "Mango":2, "Tomato":2}
items_to_buy_4

{'Potato': 3, 'Mango': 2, 'Tomato': 2}

In [78]:
items_to_buy_4  = {"Potato":3, "Mango":2, "Tomato":2 , "Potato":5}   #Here, the potato is appeared 2 times but in the output the last index potato is updated in the output
items_to_buy_4

{'Potato': 5, 'Mango': 2, 'Tomato': 2}

In [61]:
items_to_buy_4[2]

KeyError: 2

In [62]:
items_to_buy_4[2:5]

TypeError: unhashable type: 'slice'

In [66]:
items_to_buy_4.clear()

In [67]:
items_to_buy_4

{}

In [75]:
items_to_buy_4  = {"Potato":3, "Mango":2, "Tomato":2 , "Potato":5} 
items_to_buy_4

{'Potato': 5, 'Mango': 2, 'Tomato': 2}

In [76]:
items_to_buy_4.keys()

dict_keys(['Potato', 'Mango', 'Tomato'])

In [77]:
items_to_buy_4.values()

dict_values([5, 2, 2])

In [3]:
items_to_buy_4  = {"Potato":3, "Mango":2, "Tomato":2}
items_to_buy_4

{'Potato': 3, 'Mango': 2, 'Tomato': 2}

In [1]:
import pandas as pd

In [7]:
pd.DataFrame(data=items_to_buy_4)

ValueError: If using all scalar values, you must pass an index

In [13]:
math_students_mark = {"Class 1":[67,89,100,34]}

In [14]:
math_students_mark

{'Class 1': [67, 89, 100, 34]}

In [15]:
pd.DataFrame(data=math_students_mark)

   Class 1
0       67
1       89
2      100
3       34

In [18]:
math_students_mark = {"Name":["Yujin","Malini","Love","Valentine"],"Maths":[67,89,100,34],"Science":[100,90,80,70]}

In [19]:
pd.DataFrame(data=math_students_mark)

        Name  Maths  Science
0      Yujin     67      100
1     Malini     89       90
2       Love    100       80
3  Valentine     34       70